dist: trusty
language: java
sudo: false
jdk:
  - openjdk10
install: "/bin/true"
script:
  - mvn clean install -q -B
env:
  global:
    - secure: mTTiPIEx1euDAysQv6DuvamEkPOY39aLSuCQ3sAGA1YE/nRE8QOS7ybuKQqysiNTtdYk1QI7UU62xuuYRYb8+ZXqcJ8/qKYECYagzSlSxPsfcimIYL5YsQ4c3o+V9COPg9ifEEV0qmsZkYPLMxizCheCMr6Syq+5aZkDYy4qvss8PPKI7rkzExx6sA5hNyFRMS024MqpUlUkvYzv/OSwkVNAwRH/g9lKsXHMaWp1BhBPvQFrvPwv8NnIzl2/CMwJSQMozYt/mjVYnyB+L8jyBNVPGmTm0d4HzngrWblrvMIBqm8VoS/eQbpN6PY3JJwn/Hlo48fqDLBliJdCYd6xcPgx+1L70MRoOoLGyngZ1QHCX6F8ltgkiLZsbQ0g0pjGDf8PZ07Y4EwLiFxxXuCze49GIPH/u8+2uf71w8k9AuLT4LlpcjFnI5BptVxWuNzwc7w4Kpe1AABsGSdgqrpkug0gelTdDFZUenkuqCm/Ja0tIaiI9t37e5W8eVa/cbC27ftXWL/dEaTTuT5sLf/Xz/b9DckfbCPam10RfZ9Uvvf4adT0Dr0Ji4Otsygbx/iPnFwEh4fe3Y3VazC85Ib7h1A3bkfueci7sXpq9nJvIXwOZvYpAgV0WHieYxbooB21G+IopMbJ5rRkTtR2IfnlWwWpIJmnZhDNsGw2y+VzE58=
    - secure: nVSGdy/7h9S46y0+dhA3fODdNVAFL3hSQk98uShxyryRR3Ntk335cjiwIcJ+9TJzTJHh4huLjdwOKYVp2qLbxznc/3DlQV9xXGCK13xBwMamt8JxXHlgUKnA4IKtmIwQAHd8DgdmI7zbuCU5XKvNvga96CPVnVwwKbbINvoy6LGcf7OEza38g68WGJGbvb9X3nVW6HVV5PufukWCRIRNfGNAOKArji9VgeP3H9yeiUAqAkuoZD+N/+qfEFAeJAxsuEW5ct3oOI0FP/xyVD/3pqjpKBngoTzRvrAGUjoU6+RwLd6rJIHuY+KB1mf5wsUz9HlhwJtESA1mgSRaNTYtIKtjYmZ+VDZtUR2sl5aXM4m4ytvqZpzX9wXaCTCg/iSOonTn8PjVNvbZ7vM2Jy5RK59gKcycxto6nMwchrPPzok/4HgDItetMnuE5qq7/bSkUvjmM147brMidw8143WANPjkNBm2PjHT8kWrcEO/rzmSVNLhFG/pApFiDd6kEiHvL+aygjvVKhEPbxoimJo33lv4Tk/y0B8QIQAmXKhTms8+FksS+CizjDH+OD04xhWZgBA6jrLPpTV2EK9bSpjCmj33v2aCg9pEs7ofIwvu24HMG9w8O5IO3qP6qWjuEAgGn11v5+ak51iCCxrFoaooCVsuG+xKxGLXmBdpScgs83Q=
    - secure: h43onA7vMay2j8Q9RS5N5f/3YL24Nde/ht20PGeqNKVsbLytk49AdmdRmvI39nMfOCktU5egeaqN0nUjG2H4FZBSf0lZUM6u3VCc6UaAARqcwssoYXJJ7k5q1IKcAuDWFs8qnXOae1vnSLwydvj2ZOL9HTUHsEV2QpURnQgCw8UZp/qI1oSOR2RG5LufeNfisrP3X7kKBvD6531ZL5W8W74gkVAV4YlIAeDZ0Z9WSNeXmtmiavm+yZF2/AU5D7XA2P+WcWgKTQdNzzO69RG5kB/Z+UFoS0U4oFmaFELFPwYKagGA6Jo/vUnDykuqzhYnBr49YGtYHL2yROFB9op7zZfMP+tDpyIRFWviTzjsgkyWs+mG5+hXeduBFZjcWZ47Mc1gU/guX05aP18iFoxzoloDIhvJwLK4Zt1HsHW3ONcK0Ng8NbCXegx4XYCgikWvX+O7QaDafXDGNoYeKI+JSbfBDwYGaE/r9O6vJfmXqT4KldUFd9K4L29GGDOKSbnb2AecmgKdKVG2wZ+hRWIpQnmvTVuHB8BtgYAGuNyHaTHriTbCl77CeuyI1WK2fUfnxffBXdkTKXdXEtuyIxKqaA6Cz0lFuNSU2OyKkRreCPaCTz2J8h8ovJzoXLxptYhqiSktPalK+JBRXEDERlH3yxaf7RnIBrsWHtnWT6IW1tY=
    - secure: gb0inGx8vZHL0CjrBEZHeS+9Sxt8ss8jfvJ25kak64RtXi+krIdKf9jaddgHXsI9bRbZAjCiKQSsXVjZCa6FiNtkGuyfMzB6SduZn16eG0WPkNZx9cKgpdm6G4c8fINyTQMsjy6B6bSSDBFRycKAClpsDw+mYQ9p4bFR97lni8wpRGCRnUSdRhmaITN9VDbPg/nBOEBaON45UMzfIuNuaT+fQmvWDbYeuUAHVL/fXJf39M851H2391V87scemwfBvzNeWLZtmsxSxDzwyBxxQQFJvdGfNpBlq7lRqvT0FheUZMS7s48azdU68yx8CHbPfSg7BLtIeRZWWK9ClBFSVufHmf34PA/XAd4koExEmw/vm0kyo1t+HuaX7I9vd/bUtHnc8BKRMgL+LGqf06C/PWzky4Urboom/u7FO+vdiYrqXU380km1E5F3iIF0UQ25fsZGNB/rgTEj+8TYoUv5XMzSKzxnnUBLxfWRRxGg4MQ3/uCdw408uCs6pisAllEHO7l4YLvMTh20lAq+onHlLxIr+9VxTEaBHYmBPfqDyil5ZfRMomwpgVV8LxdAeFY19rUforcKPBUIhluIJ0WrRprgbk7KhRP9LwNnabO1+cKZetO+dOfQ9U2CMHfGQBRIsifTHtOCroSQ4y5DCrJxMgviZ+Gg5+Eo1yZ1F4GVKeo=
before_deploy:
  - openssl aes-256-cbc -K $encrypted_4c33f5d5b8d1_key -iv $encrypted_4c33f5d5b8d1_iv
    -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
  - skip_cleanup: true
    provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash) -t f2a66508-7c36-49cd-9da7-17ea44408b3a