package com.computablefacts.nona.functions.patternoperators;

import java.util.Set;

import org.junit.Assert;
import org.junit.Test;

import com.computablefacts.asterix.Span;
import com.computablefacts.asterix.SpanSequence;
import com.computablefacts.nona.Function;
import com.google.common.collect.Sets;

public class CompanyWithElfTest {

  /* Extracted from https://www.sec.gov/divisions/corpfin/internatl/alpha2001.htm */
  private static final Set<String> COMPANY_NAMES = Sets.newHashSet("360Networks Inc.",
      "3DLabs Inc. Ltd.", "724 Solutions Inc.", "A B Electrolux", "A B SKF", "A B Volvo",
      "A R T International Inc.", "A.O. Tatneft", "ABB Ltd.", "Abbey National plc",
      "Aber Diamond Ltd.", "Abitibi Consolidated Inc.", "ABN Amro Holding N.V.", "Acambis plc",
      "Accelio Corp.", "Acetex Corp.", "Achieva Development Corp.",
      "Acindar Industria Argentina de Aceros S.A.", "ACLN Ltd.", "ACS-Tech 80 Ltd.",
      "ActFit.com Inc.", "ActivCard S.A.", "Active Assets & Associates Inc.",
      "ADB Systems International Inc.", "Adecco S.A.", "Adrian Resources Ltd.",
      "Advance Agro Public Co. Ltd.", "Advanced Semiconductor Engineering, Inc.", "Advantest Corp.",
      "AdvantExcel.com Communications Corp.", "AEGON N.V.", "Aerco Ltd.", "AES Drax Holdings Ltd.",
      "AES Drax Power Finance Holdings Ltd.", "Aeterna Laboratories Inc.",
      "Agnico-Eagle Mines Ltd.", "Agrium Inc.", "AimGlobal Technologies Co. Inc.",
      "Ainsworth Lumber Co. Ltd.", "Air Canada", "Akzo Nobel N.V.",
      "Aladdin Knowledge Systems Ltd.", "Alberta Energy Co. Ltd.", "Alcan Inc.", "Alcatel",
      "Alestra, S de R.L. de C.V.", "Alfa Laval Special Finance AB", "Algoma Steel Inc.",
      "Alliance Atlantis Communications Corp.", "Allianz Aktiengesellschaft",
      "Allied Irish Banks plc", "Allura International Inc.", "Almaden Resource Corp.", "Alstom",
      "Altair International, Inc.", "Altarex Corp.", "Alto Palermo S.A.",
      "Aluminum Corp of China Ltd.", "Alvarion Ltd.", "Amarin Corp plc",
      "Amatek Industries Pty Ltd.", "Amcor Ltd.", "Amdocs Ltd.", "America Mineral Fields Inc.",
      "America Movil, S.A. de C.V.", "American Israeli Paper Mills Ltd.", "Amersham plc",
      "Amvescap plc", "Amway Japan Ltd.", "Anangel-American Shipholdings Ltd.",
      "Anchor Lamina, Inc.", "Angiotech Pharmaceuticals, Inc.", "Anglo Swiss Resources Inc.",
      "Anglogold Ltd.", "Anooraq Resources Corp.", "Antenna TV S.A.",
      "Anthony Clark International Insurance Brokers Inc.", "API Electronics Group Inc.",
      "Apiva.com Web Corp.", "APT Satellite Holdings Ltd.", "Aracruz Celulose S.A.",
      "Aramex International Ltd.", "ARC Energy Trust", "Arcadis N.V.", "Arch Capital Group Ltd.",
      "Archangel Diamond Co.", "Arel Communications & Software Ltd.", "Argosy Minerals Inc.",
      "Ariel Resources Ltd.", "Arm Holdings plc", "Art Advanced Research Technologies Inc.",
      "Aryt Industries Ltd.", "ASAT Holdings Ltd.", "ASE Test Ltd.", "Ashanti Goldfields Co. Ltd.",
      "Asia Pacific Resources International Ltd.", "Asia Pacific Resources, Ltd.",
      "Asia Pacific Wire & Cable Corp. Ltd.", "Asia Pulp & Paper Co. Ltd.",
      "Asia Satellite Telecommunications Holdings Ltd.", "Asiacontent.com Ltd.",
      "ASM International N.V.", "ASML Holding N.V.", "Aspen Group Resources Corp.",
      "AstraZeneca plc", "Astris Energi Inc.", "AT Plastics Inc.", "AT&T Canada Inc.",
      "ATI Technologies Inc.", "Atlantic Caspian Resources plc", "Atlantic Telecom Group plc",
      "Atlas Pacific Ltd.", "ATNA Resources Ltd.", "Attunity Ltd.", "Audiocodes Ltd.",
      "Aurizon Mines Ltd.", "Aurora Metals BVI Ltd.", "Australia & New Zealand Banking Group Ltd.",
      "Autonomy Corp plc", "Avecia Group plc", "Aventis", "AXA", "Axcan Pharma Inc.",
      "Ayotte Music Inc.", "Azteca Holdings, S.A. de C.V.", "Aztek Technologies Inc.",
      "B & H Ocean Carriers Ltd.", "Bakbone Software Inc.", "Balaton Power Inc.",
      "Ballard Power Systems Inc.", "Baltimore Technologies plc",
      "Banco Bilboa Vizcaya Argentaria S.A.", "Banco Bradesco S.A.",
      "Banco Comercial Portugues S.A.", "Banco de A. Edwards", "Banco de Chile",
      "Banco Espirito Santo e Comercial de Lisboa S.A.", "Banco Rio de la Plata S.A.",
      "Banco Santander - Chile", "Banco Santander Central Hispano S.A.", "Banco Santiago",
      "Banco Totta & Acores S.A.", "BanColombia S.A.", "Bank of Montreal",
      "Barak I.T.C. (1995) - International Telecommunications Services Corp.",
      "Barbeques Galore Ltd.", "Barclays Bank plc", "Barclays plc", "Barrick Gold Corp.",
      "BASF Aktiengesellschaft", "Battery Technologies Inc.", "Baytex Energy Ltd.",
      "BBVA Banco BHIF", "BBVA Banco Frances S.A.", "BCE Inc.", "BCI Telecom Holding Inc.",
      "BE Semiconductor Industries N.V.", "Beijing Yanhua Petrochemical Co. Ltd.", "Bell Canada",
      "Belmont Resources, Inc.", "Belzberg Technologies Inc.", "Bema Gold Corp.",
      "Benetton Group S.p.A.", "Benguet", "Bennett Environmental Inc.", "Berkley Resources Inc.",
      "Bestel S.A. de C.V.", "BG Group plc", "BHP Billiton Ltd.", "Biacore International AB",
      "Big Rock Brewery Ltd.", "Bioforest Pacific Inc.", "Biomira Inc.", "Biora AB",
      "Biovail Corporation", "Birch Mountain Resources Ltd.", "Blue Square - Israel Ltd.",
      "Boardwalk Equities Inc.", "BOC Group plc", "Bonso Electronics International Inc.",
      "Bookham Technology plc", "BOS Better Online Solutions Ltd.", "Bouygues Offshore S.A.",
      "BP plc", "Bracknell Corp.", "Bradner Ventures Ltd.", "Brandera.com Inc.", "Brascan Corp.",
      "Brasil Telecom Participacoes S.A.", "Brasil Telecom S.A.", "Bravo Resource Partners Ltd.",
      "Breakwater Resources Ltd.", "Brilliance China Automotive Holdings Ltd.",
      "British Airways plc", "British Biotech plc", "British Energy plc",
      "British Sky Broadcasting Group plc", "Brocker Technology Group Ltd.",
      "Brokat Aktiengesellschaft", "Brookfield Properties Corp.", "BT Group plc",
      "Buenos Aires Embotelladora S.A.-BAESA", "Buffalo Diamonds Ltd.", "Buhrmann N.V.",
      "Bunge Ltd.", "Bunzl plc", "BVR Systems Ltd.", "BVR Technologies Ltd.",
      "Cable and Wireless plc", "Cable Satisfaction International Inc.",
      "Cabletel Communications Corp.", "Cableuropa, S.A.", "Cablevision S.A.",
      "Cadbury Schweppes plc", "Cade Struktur Corp.", "Calais Resources Inc.", "CalciTech Ltd.",
      "Caledonia Mining Corp.", "California Exploration Ltd.", "Call Net Enterprises Inc.",
      "Callahan Nordheim-Westfalen GmbH", "Cambior Inc.", "Cambridge Antibody Technology Group plc",
      "Cameco Co.", "Camflo Resources Ltd.", "Campbell Resources Inc.", "Camtek Ltd.",
      "Camuzzi Gas del Sur S.A.", "Camuzzi Gas Pampeana S.A.", "Canada Life Financial Corp.",
      "Canada Southern Petroleum Ltd.", "Canadian 88 Energy Corp.",
      "Canadian Imperial Bank of Commerce", "Canadian National Railway Ltd.",
      "Canadian Natural Resources Ltd.", "Canadian Pacific Railway Ltd.", "Canadian Zinc Corp.",
      "Canalaska Ventures Ltd.", "Canarc Resources Corp.", "Canon Inc.",
      "CanWest Global Communications Co.", "Canwest Media Inc.",
      "Capital Environmental Resource Inc.", "Carlisle Holdings Ltd.", "Carlton Communications plc",
      "Carmanah Technologies Corp.", "Carmel Container Systems Ltd.", "CBX Ventures, Inc.",
      "CE Franklin Ltd.", "Cedara Software Corp.", "Celanese AG", "Celestica Inc.",
      "Celltech Group plc", "Celulosa Arauco y Constitucion S.A.", "Cemex, S.A. de C.V.",
      "Cenargo International plc", "Cenes Pharmaceuticals plc", "Central Fund of Canada Ltd.",
      "Central Minera Corp.", "Centurion Energy International Inc.", "Ceragon Networks Ltd.",
      "Certicom Corp.", "Ceyoniq AG", "Cez, A.S.", "CFM Majestic Inc.", "CGI Group Inc.",
      "CGU Group Canada Ltd.", "Chai-Na-Ta Corp.", "Chartered Semiconductor Manufacturing Ltd.",
      "Chartwell Technology Inc.", "CHC Helicopter Corp.", "Check Point Software Technologies Ltd.",
      "China Convergent Corp. Ltd.", "China Eastern Airlines Corp. Ltd.", "China Enterprises Ltd.",
      "China Mobile (Hong Kong) Ltd.", "China Petroleum & Chemical Corp. (Sinopec)",
      "China Southern Airlines Corp. Ltd.", "China Unicom Ltd.", "China Yuchai International Ltd.",
      "Chinadotcom Corp.", "Chipmos Technologies (Bermuda) Ltd.",
      "Ciba Speciality Chemicals Holding Inc.", "Cimatron Ltd.", "Cinema Internet Networks Inc.",
      "Cinram International Ltd.", "Citadel Gold Mines Inc.", "City Telecom (H.K.) Ltd.",
      "CityView Corp Ltd.", "Claxson Interactive Group plc", "Clearly Canadian Beverage Corp.",
      "Clearwave N.V.", "Clondalkin Industries plc", "CLP Power Hong Kong Ltd.", "Clubhaus plc",
      "CNH Global N.V.", "CNOOC Ltd.", "Coca-Cola Embonor S.A.", "Coca-Cola Femsa S.A. de C.V.",
      "Cognicase Inc.", "Cognos Inc.", "Coles Myer Ltd.", "Colt Telecom Group plc",
      "Commercial Consolidators Corp.", "Commonwealth Bank of Australia", "Commtouch Software Ltd.",
      "Compagnie Generale de Geophysique", "Companhia Brasileira de Distribuicao",
      "Companhia de Alimentos Fargo", "Companhia de Bedidas das Americas - AMBEV",
      "Companhia Energetica de Minas Gerais - CEMIG", "Companhia Parananse de Energia - Copel",
      "Companhia Siderurgica Nacional", "Companhia Vale de Rio Doce S.A.",
      "Compania Anonima Nacional Telefonos de Venezuela S.A.", "Compania Cervecerias Unidas S.A.",
      "Compania de Minas Buenaventura S.A.", "Compania de Telecomunicaciones de Chile S.A.",
      "Compania Internacional de Telecomunicaciones S.A.", "Compugen Ltd.",
      "Comunicacion Celular S.A.", "Concordia Bus AB", "Coniagas Resources Ltd",
      "Conoco Canada Resources Ltd.", "Consolidated Envirowaste Industries Inc.",
      "Consolidated Mercantile Inc.", "Consolidated Trillion Resources Ltd.",
      "Consolidated Water Co. Ltd.", "Consortium G Dina Group S.A. de C.V.",
      "Consumers Packaging Inc.", "Continental Energy Corp",
      "Controladora Comercial Mexicana S.A. de C.V.", "Converium Holding AG", "Cookson Group plc",
      "Coolbrands International Inc.", "Copamex Industries, S.A. de C.V.",
      "Copene - Petroquimica do Nordeste S.A.", "Coral Gold Corp.", "Coral Group plc",
      "Cordiant Communications Group plc", "Corel Corp.", "Corimon C.A.",
      "Corus Entertainment Inc.", "Corus Group plc", "Cott Corp.", "Counsel Corp.", "CP Ships Ltd.",
      "Crayfish Co. Ltd.", "Cream Minerals Ltd.", "Creative Technology Ltd.",
      "Creator Capital Ltd.", "Credicorp", "Credit Suisse Group", "Creo Products Inc.",
      "Cresud Sacif", "Crew Development Corp.", "CRH plc", "Cristalerias de Chile S.A.",
      "Crosswave Communications Inc.", "Crow Technologies 1977 Ltd.", "Crucell N.V.",
      "Cryopack Industries Inc.", "Cryptologic Inc.", "Crystal Graphite Corp.",
      "Crystal Systems Solutions Ltd.", "Crystallex International Corp.", "CSR Ltd.",
      "CTI Holdings S.A.", "Cumberland Resources Ltd.", "Current Technology Corp.",
      "Cusac Gold Mines Ltd.", "D G Jewelry of Canada Inc.", "DaimlerChrysler AG",
      "Dassault Systems S.A.", "Datalex plc", "Datamirror Corp.", "Datawave Systems Inc.",
      "Daugherty Resources Inc.", "Dayton Mining Co.", "De Rigo S.p.A.", "Dealcheck.com Inc.",
      "Decoma International Inc.", "Dectron Internationale Inc.", "Delano Technology Corp.",
      "Delta Galil Industries Ltd.", "Derek Resources Corp.", "Derlan Manufacturing Inc.",
      "Desc S.A. de C.V.", "Descartes Systems Group Inc.", "Deswell Industries Inc.",
      "Deutsche Bank Aktiengesellschaft", "Deutsche Telekom AG", "DF China Technology Inc.",
      "Diageo plc", "Dialog Semiconductor plc", "Digital Star Inc.", "Digitale Telekabel AG",
      "Disco S.A.", "Distribucion y Servicio D&S S.A.", "Diversinet Inc.", "Dolphin Telecom plc",
      "Doman Industries Ltd.", "Domtar Inc.", "Donner Minerals Ltd.", "Dorel Industries Inc.",
      "Dr. Reddy's Laboratories Ltd.", "Draxis Health Inc.", "DSG International Ltd.",
      "Ducati Motor Holdings S.p.A.", "Dundee Bancorp Inc.", "Durban Roodepoort Deep Ltd.",
      "Dynacare Inc.", "Dynamic Digital Depth Inc.", "Dynamic Oil & Gas Ltd.",
      "DynaMotive Energy Systems Corp.", "Dynea International Oy", "E*Comnetrix Inc.", "E.ON AG",
      "Ebookers.com plc", "Echo Bay Mines Ltd.", "ECI Telecommunications Ltd.", "Ectel Ltd.",
      "EDAP TMS S.A.", "E-digital Corp.", "EDP - Electricidade de Portugal S.A.",
      "Eganagoldpfeil (Holdings) Ltd.", "Eidos plc", "Eiger Technology Inc.", "Eimo Oyj",
      "Ek Chor China Motorcycle Company Ltd.", "Ekabel Hessen GmbH", "Eksportfinans A/S",
      "Elan Corp plc", "Elbit Ltd.", "Elbit Medical Imaging Ltd.", "Elbit Systems Ltd.",
      "Elbit Vision Systems Ltd.", "Electrochemical Industries 1952 Ltd.",
      "Elephant & Castle Group, Inc.", "Eletson Holdings Inc.", "Elron Electronic Industries Ltd.",
      "Elscint Ltd.", "Elsevier N.V.", "Eltek Ltd.", "Embotelladora Andina S.A.",
      "Embraer-Empresa Brasileira de Aeronautica S.A.", "Embratel Participacoes S.A.", "Emco Ltd.",
      "Empresa Electrica Pehuenche S.A.", "Empresa Nacional de Electricidad S.A. - Endesa",
      "Empresas ICA Sociedad Controladora S.A.", "Enbridge Inc.", "Endesa S.A.", "Enel S.p.A.",
      "Energis plc", "Energy Power Systems Ltd.", "Enerplus Resources Fund", "Enersis S.A.",
      "Engel General Developers Ltd.", "ENI S.p.A.", "Enitel ASA", "Enodis plc",
      "Enterprise Oil plc", "Enterra Energy Corp.", "Envoy Communications Group, Inc.", "EPCOS AG",
      "Equant N.V.", "Equity Finance Holding Corp.", "Esat Group Ltd", "e-Sim Ltd.",
      "Espirito Santo Centrais Eletricas S.A. - Escelsa", "Espirito Santo Financial Group S.A.",
      "Etablissements Delhaize Freres & Cie - Le Lion", "Etruscan Resources Inc.", "ETZ Lavud Ltd.",
      "Euro Disney S.C.A.", "Euro-Tech Holdings Inc.", "Eurotel Bratislava, A.S.", "EuroTrust A/S",
      "Eurozinc Mining Corp.", "Excel Maritime Carriers Ltd.",
      "Exfo Electro-Optical Engineering Inc.", "Extendicare Inc.", "Fage Dairy Industry S.A.",
      "Fahnestock Viner Holdings Inc.", "Fairfax Financial Holdings Ltd.",
      "Fairfield Minerals Ltd.", "Fairmont Hotels & Resorts Inc.", "Falconbridge Ltd.",
      "Fantom Technologies Inc.", "Fiat S.p.A.", "Fila Holdings S.p.A.", "Filtronic plc",
      "FirstService Corp.", "Fisher & Paykel Industries Ltd.", "Flag Ltd.",
      "Flamel Technologies S.A.", "Fletcher Building Ltd.", "Fletcher Challenge Forests Ltd.",
      "Flotek Industries Inc.", "Fomento Economico Mexicano S.A. de C.V.", "Forbes Medi-Tech Inc.",
      "Fording, Inc.", "Formula Systems (1985) Ltd.", "Four Seasons Hotels Inc.", "France Telecom",
      "Franklin Lake Resources Ltd.", "Fresenius Medical Care AG", "Fresh Del Monte Produce Inc.",
      "Frisco Bay Industries Ltd.", "Frontline Ltd.", "Futuremedia plc",
      "G. Willi-Food International Ltd.", "Gala Group Holdings plc", "Galen Holdings plc",
      "Gallaher Group plc", "Gearbulk Holding Ltd.", "Gee-Ten Ventures Inc.",
      "Gemplus International S.A.", "Gener S.A.", "Genesis Microchip Inc.", "Genesys S.A.",
      "Genetronics Biomedical Ltd.", "Gensci Regeneration Sciences Inc.", "Genset",
      "Gentia Software plc", "Gentry Resources Ltd.", "Gerdau S.A.", "Getgo Mail.com Ltd.",
      "Getty Copper Corp.", "Gigamedia Ltd.", "Gilat Satellite Networks Ltd.",
      "Gildan Activeware Inc.", "Given Imaging Ltd.", "Glamis Gold Ltd.", "GlaxoSmithKline plc",
      "Glencore Nickel Pty Ltd.", "Glengarry Holdings Ltd.", "Global Light Telecommunications Inc.",
      "Global SantaFe Corp.", "Global Sources Ltd.", "Global-Tech Appliances Inc.",
      "Globaltex Industries Inc.", "Globe Telecom plc", "Globetech Ventures Corp.",
      "Globex Mining Enterprises Inc.", "Globo Cabo S.A.", "Gold Reserve Inc.",
      "Goldbelt Resources Ltd.", "Goldcorp, Inc.", "Golden Nugget Exploration Inc.",
      "Golden Rule Resources Ltd.", "Golden Star Resources Ltd.", "Goran Capital Inc.",
      "Governor and Company of the Bank of Ireland", "GrandeTel Technologies Inc.",
      "Grapes Communications B.V.", "Great Basin Gold Ltd.", "Great Lakes Power Inc.",
      "Groupe Danone", "Gruma, S.A. de C.V.", "Grupo Aeroportuario del Sureste, S.A. de C.V.",
      "Grupo Azucarero, S.A. de C.V.", "Grupo Casa Saba, S.A. de C.V.", "Grupo Elektra S.A.",
      "Grupo Financiero Galicia S.A.", "Grupo Imsa S.A. de C.V.",
      "Grupo Industrial Durango S.A. de C.V.", "Grupo Industrial Maseca S.A. de C.V.",
      "Grupo Iusacell Celular, S.A. de C.V.", "Grupo Iusacell, S.A. de C.V.",
      "Grupo Minero Mexicano, S.A. de C.V.", "Grupo Radio Centro S.A. de C.V.",
      "Grupo Simec S.A. de C.V.", "Grupo Televisa S.A.", "Grupo TMM, S.A. de C.V.",
      "Grupo Tribasa S.A. de C.V.", "GSI Lumonics Inc.", "GT Group Telecom Inc.",
      "Guangshen Railway Co. Ltd.", "Guangzhou-Shenzen Superhighway Holdings Ltd.",
      "Gucci Group N.V.", "Gulf Indonesia Resources Ltd.", "Haemacure Corp.",
      "Hanaro Telecom, Inc.", "Hanson plc", "Harmony Gold Mining Co. Ltd.", "Havas Advertising",
      "HDFC Bank Ltd.", "Head Holding Unternehmensbeteiligung GMBH", "Head N.V.",
      "Healthcare Technologies Ltd.", "Hellenic Telecommunications Organization S.A. - OTE",
      "Hemosol Inc.", "Hibernia Foods plc", "Highway Holdings Ltd.", "Highwood Resources Ltd.",
      "Hilan Tech Ltd.", "Hilton Petroleum Ltd.", "Hitachi Ltd.", "HMV Media Group plc",
      "Hollinger Inc.", "Honda Motor Co. Ltd.", "Household Financial Corp. Ltd.",
      "HQI Translec Chile S.A.", "HSBC Bank plc", "HSBC Holdings plc",
      "Huaneng Power International Inc.", "Hummingbird Ltd.", "Huntingdon Life Sciences Group plc",
      "Hurricane Hydrocarbons Ltd.", "Husky Energy Inc.", "Hydro One Inc.", "Hydrogenics Corp.",
      "I.I.S. Intelligent Information Systems Ltd.", "iaNett International Systems Ltd.",
      "I-Cable Communications Ltd.", "ICICI Bank Ltd.", "ICICI Ltd.", "ICON plc",
      "ICOS Vision Systems Corp N.V.", "ICTS International N.V.", "ID Biomedical Corp.",
      "IFCO Systems N.V.", "IGN Internet Global Network Inc.", "Ilog S.A.", "IMA Exploration Inc.",
      "IMagic TV Inc.", "Imax Corp.", "Immune Network Research Ltd.",
      "IMP Industrial Mineral Park Mining Corp.", "Imperial Chemical Industries plc",
      "Imperial Ginseng Products, Ltd.", "Imperial Oil Ltd.", "Imperial Tobacco Group plc",
      "Impress Metal Packaging Holdings B.V.", "Incam AG", "Inco Ltd.", "Indigo N.V.",
      "Indo-Pacific Energy Ltd.", "Industrial Development Bank of Israel Ltd.",
      "Industrias Bachoco S.A. de C.V.", "Industrie Natuzzi S.p.A.",
      "Industriforvaltnings AB Kinnevik", "Ineos Acrylics Group Holdings plc", "Inficon Holding AG",
      "Infineon Technologies AG", "Infosys Technologies Inc.", "Infovista S.A.",
      "Infowave Software Inc.", "ING Groep N.V.", "Innogy Holdings plc", "Innova, S. de R.L.",
      "Inside Holdings Inc.", "Instrumentarium Corp.", "Instrumentation Laboratory S.p.A.",
      "Intasys Corp.", "Internacional de Ceramica S.A. de C.V.", "International Absorbents Inc.",
      "International Briquettes Holding", "International Financial Group Inc.",
      "International Freegold Mineral Development", "International Hi Tech Industries Inc.",
      "International Power plc", "International Thunderbird Gaming Corp.",
      "International Tower Hill Mines Ltd.", "International Uranium Corp.",
      "International Utility Structures Inc.", "Internet Gold - Golden Lines Ltd.",
      "Internet Initiative Japan Inc.", "Intershop Communications Aktiengesellshaft",
      "Intertape Polymer Group Inc.", "Intertek Testing Services Ltd.", "Intier Automotive Inc.",
      "Intravelnet.com Inc.", "Intrawest Corp.", "Investors Group Inc.", "Iona Technologies Ltd.",
      "Ipsco Inc.", "IRSA Inversiones y Representacions, S.A.", "Ispat International N.V.",
      "Itemus Inc.", "Ito-Yokado Co. Ltd.", "Ivanhoe Energy Inc.", "IWI Holding Ltd.",
      "iXOS Software Aktiengesellschaft", "Jacada Ltd.", "James Hardie Industries N.V.",
      "Jazztel plc", "Jefferson Smurfit plc", "Jewett Cameron Trading Co.",
      "Jilin Chemical Industrial Co. Ltd.", "Jinpan International Ltd.", "Jupiters Ltd.",
      "Kafus Industries Ltd.", "Kappa Beheer B.V.", "Kenrich Mining Corp.", "Keywest Energy Corp.",
      "Kingsway Financial Services, Inc.", "Kinross Gold Corp.",
      "Klinair Environmental Technologies Ltd.", "KLM Royal Dutch Airlines",
      "Knightsbridge Tankers Ltd.", "Komatsu Ltd.", "Koninklijke KPN N.V.", "Kookmin Bank",
      "Koor Industries Ltd.", "Korea Electric Power Corp.", "Korea Telecom Corp.",
      "Korea Thrunet Ltd.", "Kowloon-Canton Railway Corp.", "KPNQwest N.V.", "Kubota Corp.",
      "Kyocera Corp.", "Lafarge", "Laidlaw Inc.", "Lanoptics Ltd.",
      "Las Vegas from Home.com Entertainment Inc.", "Lastminute.com plc",
      "Latin American Export Bank", "Leader Mining International Inc.", "Leading Brands, Inc.",
      "Legrand", "Leica Geosystems Finance plc", "Leitch Technology Corp.", "Levon Resources Ltd.",
      "Lihir Gold Ltd.", "Linea Aerea Nacional Chile S.A.- LanChile", "LinuxWizardry Systems, Inc.",
      "Lion Bioscience Aktiengesellschaft", "Lions Gate Entertainment Corp.",
      "Liquidation World Inc.", "LJ International Ltd.", "Lloyds TSB Group plc",
      "LML Payment Systems Inc.", "Localiza Rent-a-Car S.A.", "Loewen Group Inc.",
      "LogicalOptions International Inc.", "Logitech International S.A.",
      "London Electricity Group plc", "London Pacific Group Ltd.", "Lorus Therapeutics Inc.",
      "Lund Ventures Ltd.", "Luxfer Holdings plc", "Luxottica Group S.p.A.",
      "LVMH Moet-Hennessy Louis Vuitton", "Macronix International Co.",
      "Mad Catz Interactive, Inc.", "Madeco S.A.", "Madge Networks N.V.",
      "Madison Enterprises Corp.", "Magal Security Systems Ltd.", "Magic Software Enterprises Ltd.",
      "Magna International Inc.", "Magyar Tavkozlesi RT. - MATAV", "Mahanagar Telephone Nigam Ltd.",
      "Makita Corp.", "Manhattan Minerals Corp.", "Manulife Financial Corp.", "Marconi plc",
      "Marnetics Broadband Technologies Ltd.", "Marsulex Inc.", "Masisa S.A.",
      "Masonite International Corp.", "Matav Cable Systems Media Ltd.",
      "Matsushita Electric Industrial Co.", "Maxcom Telecomunicaciones, S.A. de C.V.",
      "Mayne Nickless Ltd.", "MC Shipping Inc", "MDC Co.", "MDS Inc.",
      "MDSI Mobile Data Solutions Inc.", "Med Emerg International Ltd.",
      "Med Net International Ltd.", "Mentergy Ltd.", "MEPC plc",
      "Mer Telemanagement Solutions Ltd.", "Merant plc", "Mercury Partners & Co. Inc.",
      "Mercury Scheduling Systems Inc.", "Meridian Gold Inc.", "Messer Griesheim Holding AG",
      "Metal Storm Ltd.", "Metalink Ltd.", "Metallica Resources Inc.", "Methanex Corp.",
      "Metro International S.A.", "MetroGas S.A.", "Metso Oy", "MFC Bancorp Ltd.",
      "Microcell Telecommunications Inc.", "Micrologix Biotech, Inc.", "Micromem Technologies Inc.",
      "Midland Bank plc", "MIH Ltd.", "Millar Western Forest Products Ltd.",
      "Millenium Seacarriers, Inc.", "Millicom International Cellular S.A.",
      "Minco Mining and Metals Corp.", "Mind C.T.I. Ltd.", "Minefinders Corp. Ltd.", "Mirae Corp.",
      "Miramar Mining Co.", "Mirtronics Inc.", "Misty Mountain Gold Ltd.",
      "Mitsubishi Tokyo Financial Group, Inc.", "Mitsui & Company Ltd.",
      "Mitsui Sumitomo Insurance Co. Ltd.", "mmO2 plc", "Mobile Telesystems OJSC",
      "Modern Times Group MTG AB", "Moore Corp. Ltd.", "Mountain Province Diamonds, Inc.",
      "M-Systems Flash Disk Pioneers Ltd.", "MTR Corp.", "Multicanal S.A.",
      "Murrin Murrin Holdings Pty Ltd.", "Nam Tai Electronics Inc.", "Namibian Minerals Corp.",
      "National Australia Bank Ltd.", "National Bank of Greece S.A.", "National Grid Group plc",
      "National Westminster plc", "NCE Petrofund Ltd.", "NDS Group plc", "NDT Ventures Ltd.",
      "NEC Corp.", "Nera ASA", "Net Matrix Ltd.", "Net Nanny Software International Inc.",
      "Net Sat Servicos Ltda.", "Netco Energy Inc.", "Netease.com Inc.", "Netia Holdings S.A.",
      "Nettron.com Corp.", "New China Homes, Ltd.", "New Millennium Metals Corp.",
      "New Skies Satellites N.V.", "New Tel Ltd.", "New York Broker Deutschland AG",
      "NewKidCo International Inc.", "News Corporation Ltd.", "Nexen Inc.",
      "Nexus Telocation Systems Ltd.", "Nice Systems Ltd.", "Nicholas Financial Inc.",
      "Nidec Corp.", "Nippon Telegraph and Telephone Corp.",
      "Noga Electro-Mechanical Industries (1986) Ltd.", "Nokia Corp.", "Nomura Holdings, Inc.",
      "Norampac Inc.", "Noranda Inc.", "Nord Pacific Ltd.", "Nordic American Tanker Shipping Ltd.",
      "Normandy Yandal Operations Ltd.", "Norsat International Inc.", "Norsk Hydro A/S",
      "Nortel Inversora S.A.", "Nortel Networks Corp.", "North American Palladium Ltd.",
      "Northern Crown Mines Ltd.", "Northern Offshore ASA", "Northern Rock plc",
      "Nortran Pharmaceuticals Inc.", "Nova Chemicals Corp.", "Nova Gas Transmission Ltd.",
      "Nova Measuring Instruments Ltd.", "Novamerican Steel Inc.", "Novartis AG", "NovAtel Inc.",
      "Novel Denim Holdings Ltd.", "Novogen Ltd.", "Novo-Nordisk A/S", "Nur Macroprinters Ltd.",
      "Nymox Pharmaceutical Corp.", "O&Y Properties Corp.", "O2micro International Ltd.",
      "Occidente y Caribe Celular S.A.", "Oce N.V.", "Ocean Rig ASA", "Officeland Inc.",
      "Olicom A/S", "Olympic Resources Ltd.", "Omninet International Ltd.",
      "Oncolytics Biotech Inc.", "Open Joint Stock Company of Long Distance - Rostelecom",
      "Open Text Co.", "OpenTV Ltd.", "Optibase Ltd.", "Optimal Robotics Corp.", "Orange plc",
      "Orbital Engine Corp Ltd.", "Orbotech Ltd.", "Orchestream Holdings plc",
      "Orckit Communications Ltd.", "Orient-Express Hotels Ltd.", "Origin Energy Ltd.",
      "Orix Corp.", "Oromin Explorations Ltd.", "Orthofix International N.V.",
      "Oxford Glycosciences plc", "P&O Princess Cruises plc",
      "P.T. Indah Kiat Pulp & Paper Corp Tbk", "P.T. Indonesian Satellite Corp. Tbk",
      "P.T. Pabrik Kertas Tjiwi Kimia Tbk", "P.T. Pasifik Satelit Nusantara Tbk",
      "P.T. Pindo Deli Pulp & Paper Mills", "P.T. Telekomunikasi Indonesia Tbk",
      "P.T. Tri Polyta Indonesia Tbk", "Pacific Century Cyberworks Ltd.", "Pacific Dunlop Ltd.",
      "Pacific Internet Ltd.", "Pacific North West Capital Corp.", "Pacific Rim Mining Corp.",
      "Pacifica Papers Inc.", "Paladin Resources NL", "Pan American Silver Co.",
      "PanCanadian Energy Ltd.", "Paperboard Industries International Corp.",
      "Paradigm Geophysical Ltd.", "Parthus Technologies plc", "Partner Communications Co. Ltd.",
      "PartnerRe Ltd.", "Pcom AG", "PDVSA Finance Ltd.", "Peace Arch Entertainment Group Inc.",
      "Peaksoft Multinet Corp.", "Pearson plc", "Pechiney", "Pepsi-Gemex S.A. de C.V.",
      "Perdigao S.A.", "Perez Companc S.A.", "Perle Systems Ltd.", "Peruvian Gold Ltd.",
      "Petro-Canada", "PetroChina Co. Ltd.", "Petroleo Brasileiro S.A. - Petrobras",
      "Petroleos de Venezuela", "Petroleos Mexicanos (Pemex)", "Petroleum Geo-Services A/S",
      "Petromin Resources Ltd.", "Petsec Energy Ltd.", "Pfeiffer Vacuum Technology AG",
      "Philippine Long Distance Telephone Co.", "Philips Electronics N.V.",
      "Photochannel Networks Inc.", "Pioneer Corp.", "Pivotal Corp.", "PKI Solutions Inc.",
      "Placer Dome Inc.", "Plaintree Systems Ltd.", "Playstar Corp.", "PLC Systems Inc.",
      "Pohang Iron & Steel Co. Ltd.", "Polska Telefonia Cyfrowa Sp Z o o.",
      "Polyair Inter Pack Inc.", "Polymet Mining Corp.", "Portal Net Ltd.",
      "Portrush Petroleum Corp.", "Portugal Telecom, SGPS, S.A.", "Potash Corp. of Saskatchewan",
      "PowerGen plc", "Precision Drilling Corp.", "Preem Holdings AB", "Premier Farnell plc",
      "Premier International Foods plc", "PrimaCom AG", "Princeton Media Group Inc.",
      "Professional Staff plc", "Progen Industries Ltd.", "Pro-Market Global plc", "Protherics plc",
      "Provalis plc", "Provida Pension Fund Administrator", "Provident Energy Trust",
      "Prudential plc", "PSi Technologies Holdings, Inc.", "Publicis Groupe S.A.",
      "Publicis-Ariely Ltd.", "Pyng Technologies Corp.", "QI Systems Inc.", "Qiagen N.V.",
      "Qiao Xing Universal Telephone, Inc.", "QLT Inc.", "QSC AG", "QSound Labs Inc.",
      "Quartz Mountain Gold Corp.", "Quebecor Inc.", "Quebecor Media Inc.", "Quebecor World Inc.",
      "Queenstake Resources Ltd.", "Quilmes Industrial Quinsa S.A.", "Quinenco S.A.",
      "Quintalinux Ltd.", "QXL Ricardo plc", "Rada Electronic Industries Ltd.", "Radcom Ltd.",
      "Radica Games Ltd.", "Radius Explorations Ltd.", "Radvision Ltd.", "Radware Ltd.",
      "Randgold & Exploration Co. Ltd.", "Range Petroleum Corp.", "Rank Group plc",
      "Realax Software AG", "Receptagen, Ltd.", "Rediff.com India Ltd.", "Reed International plc",
      "Reg Technologies Inc.", "Regional Independent Media Group plc", "Regus plc",
      "Repadre Capital Corp.", "Repsol YPF S.A.", "Republic Goldfields Inc.",
      "Research in Motion Ltd.", "Resource Finance & Investments Ltd.", "Retalix Ltd.",
      "Reuters Group plc", "Revenue Properties Co. Ltd.", "Rhodia", "Richmont Mines Inc.",
      "Ricoh Company Ltd.", "Rio Algom Ltd.", "Rio Narcea Gold Mines Ltd.", "Rio Tinto Ltd.",
      "Rio Tinto plc", "RIT Technologies Ltd.", "Ritchie Bros. Auctioneers Inc.",
      "Riverdeep Group plc", "RoboGroup T.E.K. Ltd.", "Robomatix Technologies Ltd.",
      "Rockwell Ventures Inc.", "Rogers Communications Inc.", "Rogers Wireless Communications Inc.",
      "Rosedale Decorative Products Ltd.", "Royal & Sun Alliance Insurance Group plc",
      "Royal Ahold Ltd. - Koninklijke Ahold N.V.", "Royal Bank of Canada",
      "Royal Bank of Scotland Group", "Royal Caribbean Cruises Ltd.", "Royal Dutch Petroleum Co.",
      "Royal Group Technologies Ltd.", "Royal Olympic Cruise Lines Inc.",
      "Royal Standard Minerals Inc.", "Rtica Corp.", "Rubicon Minerals Corp.", "Russel Metals Inc.",
      "Ryanair Holdings plc", "Sadia S.A.", "SAES Getters S.p.A.", "Samex Mining Corp.",
      "San Antonios Resources Inc.", "San Telmo Resources Ltd.", "Sand Technology Inc.",
      "Sanpaolo-IMI S.p.A.", "Santa Isabel S.A.", "SAP Aktiengesellschaft",
      "Sapiens International Corp. N.V.", "Sappi Ltd.", "Satelites Mexicanos S.A. de C.V.",
      "Satyam Computer Services Ltd.", "Satyam Infoway Ltd.", "Savia, S.A. de C.V.",
      "SBS Broadcasting S.A.", "Scania AB", "Schering Aktiengesellschaft",
      "Schroder Ventures International Investment Trust", "Scitex Corp. Ltd.", "Scoot.com plc",
      "SCOR", "Scottish Power plc", "SCS Solars Computing Systems Inc.", "Sea Containers Ltd.",
      "Seat Pagine Gialle S.p.A.", "Secureview Systems Inc.", "Sense Technologies Inc.",
      "Serono S.A.", "Seven Seas Petroleum Inc.", "SGL Carbon Aktiengesellschaft",
      "Sharpe Resources Corp.", "Shaw Communications Inc.", "Shell Canada Ltd.",
      "Shell Transport and Trading Co. Ltd.", "Siderca S.A.I.C.", "Sideware Systems Inc.",
      "Siemens Aktiengesellschaft", "Sierra Wireless, Inc.", "Signet Group plc",
      "Silent Witness Enterprises Inc.", "Silicom Ltd.",
      "Siliconware Precision Industries Co. Ltd.", "Silver Standard Resources Inc.",
      "Silverado Gold Mines Ltd.", "Silverline Technologies Ltd.", "Sina.com",
      "Sinopec Shanghai Petrochemical Co. Ltd.", "Six Continents plc", "SK Telecom Corp.",
      "Skyepharma plc", "SmarTire Systems Inc.", "Smartlogik Group plc", "Smedvig ASA",
      "Smith & Nephew plc", "Softcare EC.com Inc.", "Sonera Corp.", "Song Networks Holding AB",
      "Song Networks N.V.", "Sonus Corp.", "Sony Corp.", "Sopheon plc",
      "Southwestern Resources Corp.", "Sparkling Spring Water Group Ltd.",
      "Spectrum Signal Processing Inc.", "Spirent plc", "Sportech plc", "Spur Ventures Inc.",
      "SQM - Sociedad Quimica y Minera S.A.", "ST Assembly Test Services Ltd.",
      "Stagecoach Holdings plc", "Stake Technology Ltd.", "Star Choice Communications Inc.",
      "Star Resources Corp.", "Starfield Resources Inc.", "Stargate Entertainment Inc.",
      "Statoil ASA", "Stelmar Shipping Ltd.", "Stena Line AB",
      "STET Hellas Telecommunications S.A.", "STMicroelectronics N.V.",
      "Stockscape.com Technology Inc.", "Stolt Nielsen S.A.", "Stolt Offshore S.A.",
      "Stora Enso OYJ", "Stressgen Biotechnologies Corp.", "Suez", "Sulzer Medica Ltd.",
      "Sun International Hotels Ltd.", "Sun Life Financial Services of Canada", "Sun Media Corp.",
      "Suncor Energy Inc.", "Sunday Communications Ltd.", "Sungold Entertainment Corp.",
      "Supermercados Unimarc S.A.", "Super-Sol Ltd.", "Swedish Export Credit Corp.",
      "Swedish Match AB", "Swisscom", "Syngenta AG", "SYNSORB Biotech Inc.",
      "T.V.G. Technologies Ltd.", "Taiwan Semiconductor Manufacturing Co. Ltd.",
      "Talisman Energy Inc.", "Talisman Enterprise Inc.", "Taro Pharmaceutical Industries Ltd.",
      "Taseko Mines Ltd.", "TAT Technologies Ltd.", "TDC A/S", "TDK Corp.",
      "TDL Infomedia Group plc", "Technip-Coflexip", "Techsite Strategies Corp.", "Teck Ltd.",
      "Tecnomatix Technologies Ltd.", "Teekay Shipping Inc.", "Tefron Ltd.",
      "Tele Celular Sul Participacoes S.A.", "Tele Centro Oeste Celular Participacoes S.A.",
      "Tele Leste Celular Participacoes S.A.", "Tele Nordeste Celular Participacoes S.A.",
      "Tele Norte Celular Participacoes S.A.", "Tele Norte Leste Participacoes S.A.",
      "Tele Sudeste Celular Participacoes S.A.", "Tele2 AB", "Telebras S.A.",
      "Telecom Argentina STET France Telecom S.A.", "Telecom Corp of New Zealand Ltd.",
      "Telecom Italia S.p.A.", "Telecomunicaios de Sao Paulo S.A. - Telesp",
      "Telefonaktiebolaget L M Ericsson", "Telefonica de Argentina S.A.",
      "Telefonica del Peru S.A.", "Telefonica Holding of Argentina, Inc.",
      "Telefonica Moviles, S.A.", "Telefonica S.A.", "Telefonos de Mexico S.A. de C.V.",
      "Teleglobe Inc.", "Telekom Austria", "Telemig Celular Participacoes S.A.", "Telenor ASA",
      "Telesis North Communications Inc.", "Telesp Celular Participacoes S.A.",
      "Telesystem International Wireless Inc.", "TeleWest Communications plc", "Telex Chile S.A.",
      "Telstra Corp Ltd.", "Telus Corp.", "Tembec Industries Inc.", "Terra Networks S.A.",
      "Terra Nova Bermuda Holdings Ltd.", "Tesco Corp.", "Tesma International Inc.",
      "Teva Pharmaceutical Industries Ltd.", "Tevecap S.A.", "Texon International plc",
      "TFM, S.A. de C.V.", "Thermo Tech Technologies Corp.", "Thinkpath.com Inc.", "Thomson Corp",
      "Thomson Multimedia", "Thrilltime Entertainment International Inc.", "Thrush Industries Inc.",
      "Tioga Technologies Ltd.", "Titan Trading Analytics Inc.", "TLC The Laser Center Inc.",
      "TM Group Holdings plc", "Tokio Marine & Fire Insurance Co., Ltd.", "Tomkins plc",
      "Toolex International N.V.", "Top Image Systems Ltd.", "Toronto-Dominion Bank",
      "TotalFinaElf S.A.", "Tower Semiconductor Ltd.", "Toyota Motor Corp.", "TPG N.V.",
      "TPN Holdings plc", "Tracer Petroleum Corp.", "Trade Wind Communications Ltd.",
      "Trader.com N.V.", "TradeRadius Online Inc.", "Tramford International Ltd.",
      "TransAlta Corp.", "TransCanada Pipelines Ltd.", "Transco plc", "Transcom Worldwide S.A.",
      "Transgene S.A.", "Transglobe Energy Corp.", "Trans-Orient Petroleum Inc.",
      "Transportadora de Gas del Sur S.A.", "Transtel S.A.", "Tranz Rail Holdings Ltd.",
      "Travelex plc", "Trenche Electric S.A.", "Trend Micro Inc.", "Triant Technologies Inc.",
      "Triband Resource Corp.", "Tricom, S.A.", "Trimark Oil & Gas Ltd.", "Trinity Biotech plc",
      "Trintech Group plc", "Triple P N.V.", "Trivalence Mining Corp.", "Trizec Hahn Corp.",
      "Trooper Technologies Inc.", "TTI Team Telecom International Ltd.",
      "Tubos de Acero de Mexico S.A.", "Turbodyne Technologies Inc.",
      "Turkcell Iletisim Hizmetleri AS", "TV Azteca, S.A. de C.V.", "TVX Gold Inc.",
      "Twin Mining Corp.", "UBS AG", "Ultra Petroleum Corp.", "Ultrapar Participacoes S.A.",
      "Ultrapetrol (Bahamas) Ltd.", "Unibail", "Unibanco Holdings S.A.",
      "Unibanco-Uniao de Bancos Brasileiros S.A.", "Uniglobe.com Inc.", "Unilens Vision Inc.",
      "Unilever N.V.", "Unilever plc", "United Biscuits Finance plc", "United Business Media plc",
      "United Microelectronics Corp.", "United Utilities plc", "Universal Domains Inc.",
      "UPM Kymmene Miramichi Inc.", "UPM-Kymmene OYJ", "Usinor Sacilor", "UTi Worldwide Inc.",
      "Van der Moolen Holding N.V.", "Vancan Capital Corp.", "Vannessa Ventures Ltd.",
      "Vantico Group S.A.", "Vasogen, Inc.", "Venture Pacific Development Corp.",
      "Verena Minerals Corp.", "Veritas Holdings GmbH", "Vernalis Group plc",
      "Veronex Technologies Inc.", "Versatel Telecom International N.V.", "VI Group plc",
      "Videsh Sanchar Nigam Ltd.", "Vimpel Communications", "Vina Concha y Toro S.A.",
      "Virgin Express Holdings plc", "Virginia Gold Mines Inc.", "VirtualSellers.com Inc",
      "Viryanet Ltd.", "Visible Genetics Inc.", "Vista Gold Corp.", "Vitran Co. Ltd.", "Vitro S.A.",
      "Vivendi Environment", "Vivendi Universal", "Vocaltec Communications Ltd.",
      "Vodafone Group plc", "VoiceIQ Inc.", "Votorantim Celulose e Papel S.A.",
      "W.P. Stewart & Co. Ltd.", "Wacoal Corp.", "Waterford Wedgwood plc",
      "Waterford Wedgwood UK plc", "Wavecom S.A.", "Wescast Industries Inc.", "Westaim Corp.",
      "Westcoast Energy Inc.", "Westpac Banking Corp.", "Wharf Holdings Ltd.",
      "WideCom Group, Inc.", "William Hill Ltd.", "Willis Group Holdings Ltd.", "Willis Group Ltd.",
      "Wipro Ltd.", "WMC Ltd.", "Wolseley plc", "Workstream Inc.", "World Gaming plc",
      "World Heart Corp.", "World Ventures Inc.", "WorldWide Technologies Inc.", "WPP Group plc",
      "Xcelera.com Inc.", "Xeikon N.V.", "Xenova Group plc", "Yanzhou Coal Mining Co. Ltd.",
      "Yellow Pages Ltd.", "Yorkshire Power Group Ltd.", "YPF S.A.", "Zarlink Semiconductor Inc.",
      "Zemex Corp.", "Zi Corp.", "Ztest Electronics Inc.");

  private static final Set<String> COMPANY_NO_MATCH = Sets.newHashSet("SCOR",
      "Chipmos Technologies (Bermuda) Ltd.", "Unibail", "China Mobile (Hong Kong) Ltd.",
      "Banco Santander - Chile", "BASF Aktiengesellschaft", "A B Electrolux", "A.O. Tatneft",
      "Bank of Montreal", "Rhodia", "Pechiney", "Deutsche Bank Aktiengesellschaft", "Benguet",
      "Ebookers.com plc", "Uniglobe.com Inc.", "Banco Santiago",
      "P.T. Pindo Deli Pulp & Paper Mills", "mmO2 plc", "Sina.com", "City Telecom (H.K.) Ltd.",
      "Netease.com Inc.", "Petroleos Mexicanos (Pemex)",
      "Noga Electro-Mechanical Industries (1986) Ltd.", "Corimon C.A.",
      "Sun Life Financial Services of Canada", "Swisscom", "Mind C.T.I. Ltd.", "Technip-Coflexip",
      "Companhia Brasileira de Distribuicao", "Legrand", "Intravelnet.com Inc.",
      "Provida Pension Fund Administrator", "Brandera.com Inc.", "Aventis",
      "Lion Bioscience Aktiengesellschaft", "Eganagoldpfeil (Holdings) Ltd.", "Banco de Chile",
      "P.T. Tri Polyta Indonesia Tbk", "Genset", "Compagnie Generale de Geophysique", "Alcatel",
      "ACS-Tech 80 Ltd.", "Companhia Parananse de Energia - Copel", "Royal Bank of Canada",
      "Triple P N.V.", "VirtualSellers.com Inc", "Petro-Canada", "Kookmin Bank",
      "Vimpel Communications", "E-digital Corp.", "Thomson Multimedia", "KLM Royal Dutch Airlines",
      "International Freegold Mineral Development", "LVMH Moet-Hennessy Louis Vuitton",
      "Softcare EC.com Inc.", "BBVA Banco BHIF", "Air Canada", "Usinor Sacilor",
      "Electrochemical Industries 1952 Ltd.", "Asiacontent.com Ltd.",
      "Companhia Energetica de Minas Gerais - CEMIG", "Latin American Export Bank",
      "Commonwealth Bank of Australia", "Companhia Siderurgica Nacional", "A B SKF",
      "Brokat Aktiengesellschaft", "P.T. Pabrik Kertas Tjiwi Kimia Tbk", "Scoot.com plc",
      "Crow Technologies 1977 Ltd.", "Credit Suisse Group", "A B Volvo", "Xcelera.com Inc.",
      "Havas Advertising", "Ultrapetrol (Bahamas) Ltd.", "Groupe Danone",
      "Companhia de Bedidas das Americas - AMBEV", "iXOS Software Aktiengesellschaft",
      "ActFit.com Inc.", "Enerplus Resources Fund", "Bell Canada",
      "P.T. Telekomunikasi Indonesia Tbk", "360Networks Inc.", "RoboGroup T.E.K. Ltd.",
      "Schering Aktiengesellschaft", "Etablissements Delhaize Freres & Cie - Le Lion",
      "Siemens Aktiengesellschaft", "Trader.com N.V.", "Thinkpath.com Inc.", "Credicorp",
      "Toronto-Dominion Bank", "SGL Carbon Aktiengesellschaft", "Telekom Austria", "France Telecom",
      "Lastminute.com plc", "Distribucion y Servicio D&S S.A.", "Dealcheck.com Inc.",
      "International Briquettes Holding", "Intershop Communications Aktiengesellshaft",
      "Petroleos de Venezuela", "Companhia de Alimentos Fargo", "Telefonaktiebolaget L M Ericsson",
      "Lafarge", "Nettron.com Corp.", "Suez", "Royal Bank of Scotland Group", "Vivendi Environment",
      "AXA", "3DLabs Inc. Ltd.", "Vivendi Universal", "Allianz Aktiengesellschaft",
      "Mobile Telesystems OJSC", "Canadian Imperial Bank of Commerce",
      "Formula Systems (1985) Ltd.", "Cresud Sacif", "Getgo Mail.com Ltd.", "Alstom",
      "Net Sat Servicos Ltda.", "P.T. Pasifik Satelit Nusantara Tbk", "SAP Aktiengesellschaft");

  private static final Set<String> COMPANY_PARTIAL_MATCH =
      Sets.newHashSet("Royal Ahold Ltd. - Koninklijke Ahold N.V.",
          "Barak I.T.C. (1995) - International Telecommunications Services Corp.");

  private static final Set<String> COMPANY_FULL_MATCH =
      Sets.difference(COMPANY_NAMES, Sets.union(COMPANY_NO_MATCH, COMPANY_PARTIAL_MATCH));

  private static final Set<String> COMPANY_IN_TEXT = Sets.newHashSet();

  @Test
  public void testFullMatch() {

    for (String cpy : COMPANY_FULL_MATCH) {

      Function fn = new Function("MATCH_COMPANY_NAME(" + Function.wrap(cpy) + ")");
      SpanSequence spans = (SpanSequence) fn.evaluate(Function.definitions()).value();
      Span span = spans.span(0);

      Assert.assertEquals(1, spans.size());
      Assert.assertTrue(span.hasTag("COMPANY_NAME"));
      Assert.assertNotNull(span.getFeature("COMPANY_NAME"));
      Assert.assertNotNull(span.getFeature("LEGAL_FORM"));
    }
  }

  @Test
  public void testPartialMatch() {

    for (String cpy : COMPANY_PARTIAL_MATCH) {

      Function fn = new Function("MATCH_COMPANY_NAME(" + Function.wrap(cpy) + ")");
      SpanSequence spans = (SpanSequence) fn.evaluate(Function.definitions()).value();

      Assert.assertEquals(2, spans.size());
    }
  }

  @Test
  public void testNoMatch() {

    for (String cpy : COMPANY_NO_MATCH) {

      Function fn = new Function("MATCH_COMPANY_NAME(" + Function.wrap(cpy) + ")");
      SpanSequence spans = (SpanSequence) fn.evaluate(Function.definitions()).value();

      Assert.assertEquals(0, spans.size());
    }
  }

  @Test
  public void testExtractValidCompanyNameFromText() {

    for (String cpy : COMPANY_IN_TEXT) {

      Function fn = new Function("MATCH_COMPANY_NAME(" + Function.wrap(cpy) + ")");
      SpanSequence spans = (SpanSequence) fn.evaluate(Function.definitions()).value();
      Span span = spans.span(0);

      Assert.assertEquals(1, spans.size());
      Assert.assertTrue(span.hasTag("COMPANY_NAME"));
      Assert.assertNotNull(span.getFeature("COMPANY_NAME"));
      Assert.assertNotNull(span.getFeature("LEGAL_FORM"));
    }
  }
}
