// Generated by Snowball 2.0.0 - https://snowballstem.org/

package org.tartarus.snowball.ext;

import org.tartarus.snowball.Among;

/**
 * This class implements the stemming algorithm defined by a snowball script.
 * <p>
 * Generated by Snowball 2.0.0 - https://snowballstem.org/
 * </p>
 */
@SuppressWarnings("unused")
public class greekStemmer extends org.tartarus.snowball.SnowballStemmer {

  private static final long serialVersionUID = 1L;

  private final static Among a_0[] = {new Among("", -1, 25), new Among("\u0386", 0, 1),
      new Among("\u0388", 0, 5), new Among("\u0389", 0, 7), new Among("\u038A", 0, 9),
      new Among("\u038C", 0, 15), new Among("\u038E", 0, 20), new Among("\u038F", 0, 24),
      new Among("\u0390", 0, 7), new Among("\u0391", 0, 1), new Among("\u0392", 0, 2),
      new Among("\u0393", 0, 3), new Among("\u0394", 0, 4), new Among("\u0395", 0, 5),
      new Among("\u0396", 0, 6), new Among("\u0397", 0, 7), new Among("\u0398", 0, 8),
      new Among("\u0399", 0, 9), new Among("\u039A", 0, 10), new Among("\u039B", 0, 11),
      new Among("\u039C", 0, 12), new Among("\u039D", 0, 13), new Among("\u039E", 0, 14),
      new Among("\u039F", 0, 15), new Among("\u03A0", 0, 16), new Among("\u03A1", 0, 17),
      new Among("\u03A3", 0, 18), new Among("\u03A4", 0, 19), new Among("\u03A5", 0, 20),
      new Among("\u03A6", 0, 21), new Among("\u03A7", 0, 22), new Among("\u03A8", 0, 23),
      new Among("\u03A9", 0, 24), new Among("\u03AA", 0, 9), new Among("\u03AB", 0, 20),
      new Among("\u03AC", 0, 1), new Among("\u03AD", 0, 5), new Among("\u03AE", 0, 7),
      new Among("\u03AF", 0, 9), new Among("\u03B0", 0, 20), new Among("\u03C2", 0, 18),
      new Among("\u03CA", 0, 7), new Among("\u03CB", 0, 20), new Among("\u03CC", 0, 15),
      new Among("\u03CD", 0, 20), new Among("\u03CE", 0, 24)};

  private final static Among a_1[] = {new Among("\u03C3\u03BA\u03B1\u03B3\u03B9\u03B1", -1, 2),
      new Among("\u03C6\u03B1\u03B3\u03B9\u03B1", -1, 1),
      new Among("\u03BF\u03BB\u03BF\u03B3\u03B9\u03B1", -1, 3),
      new Among("\u03C3\u03BF\u03B3\u03B9\u03B1", -1, 4),
      new Among("\u03C4\u03B1\u03C4\u03BF\u03B3\u03B9\u03B1", -1, 5),
      new Among("\u03BA\u03C1\u03B5\u03B1\u03C4\u03B1", -1, 6),
      new Among("\u03C0\u03B5\u03C1\u03B1\u03C4\u03B1", -1, 7),
      new Among("\u03C4\u03B5\u03C1\u03B1\u03C4\u03B1", -1, 8),
      new Among("\u03B3\u03B5\u03B3\u03BF\u03BD\u03BF\u03C4\u03B1", -1, 11),
      new Among("\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4\u03C9\u03C4\u03B1", -1, 10),
      new Among("\u03C6\u03C9\u03C4\u03B1", -1, 9),
      new Among("\u03C0\u03B5\u03C1\u03B1\u03C4\u03B7", -1, 7),
      new Among("\u03C3\u03BA\u03B1\u03B3\u03B9\u03C9\u03BD", -1, 2),
      new Among("\u03C6\u03B1\u03B3\u03B9\u03C9\u03BD", -1, 1),
      new Among("\u03BF\u03BB\u03BF\u03B3\u03B9\u03C9\u03BD", -1, 3),
      new Among("\u03C3\u03BF\u03B3\u03B9\u03C9\u03BD", -1, 4),
      new Among("\u03C4\u03B1\u03C4\u03BF\u03B3\u03B9\u03C9\u03BD", -1, 5),
      new Among("\u03BA\u03C1\u03B5\u03B1\u03C4\u03C9\u03BD", -1, 6),
      new Among("\u03C0\u03B5\u03C1\u03B1\u03C4\u03C9\u03BD", -1, 7),
      new Among("\u03C4\u03B5\u03C1\u03B1\u03C4\u03C9\u03BD", -1, 8),
      new Among("\u03B3\u03B5\u03B3\u03BF\u03BD\u03BF\u03C4\u03C9\u03BD", -1, 11),
      new Among("\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4\u03C9\u03C4\u03C9\u03BD", -1, 10),
      new Among("\u03C6\u03C9\u03C4\u03C9\u03BD", -1, 9),
      new Among("\u03BA\u03C1\u03B5\u03B1\u03C3", -1, 6),
      new Among("\u03C0\u03B5\u03C1\u03B1\u03C3", -1, 7),
      new Among("\u03C4\u03B5\u03C1\u03B1\u03C3", -1, 8),
      new Among("\u03B3\u03B5\u03B3\u03BF\u03BD\u03BF\u03C3", -1, 11),
      new Among("\u03BA\u03C1\u03B5\u03B1\u03C4\u03BF\u03C3", -1, 6),
      new Among("\u03C0\u03B5\u03C1\u03B1\u03C4\u03BF\u03C3", -1, 7),
      new Among("\u03C4\u03B5\u03C1\u03B1\u03C4\u03BF\u03C3", -1, 8),
      new Among("\u03B3\u03B5\u03B3\u03BF\u03BD\u03BF\u03C4\u03BF\u03C3", -1, 11),
      new Among("\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4\u03C9\u03C4\u03BF\u03C3", -1, 10),
      new Among("\u03C6\u03C9\u03C4\u03BF\u03C3", -1, 9),
      new Among("\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4\u03C9\u03C3", -1, 10),
      new Among("\u03C6\u03C9\u03C3", -1, 9),
      new Among("\u03C3\u03BA\u03B1\u03B3\u03B9\u03BF\u03C5", -1, 2),
      new Among("\u03C6\u03B1\u03B3\u03B9\u03BF\u03C5", -1, 1),
      new Among("\u03BF\u03BB\u03BF\u03B3\u03B9\u03BF\u03C5", -1, 3),
      new Among("\u03C3\u03BF\u03B3\u03B9\u03BF\u03C5", -1, 4),
      new Among("\u03C4\u03B1\u03C4\u03BF\u03B3\u03B9\u03BF\u03C5", -1, 5)};

  private final static Among a_2[] =
      {new Among("\u03C0\u03B1", -1, 1), new Among("\u03BE\u03B1\u03BD\u03B1\u03C0\u03B1", 0, 1),
          new Among("\u03B5\u03C0\u03B1", 0, 1),
          new Among("\u03C0\u03B5\u03C1\u03B9\u03C0\u03B1", 0, 1),
          new Among("\u03B1\u03BD\u03B1\u03BC\u03C0\u03B1", 0, 1),
          new Among("\u03B5\u03BC\u03C0\u03B1", 0, 1), new Among("\u03B4\u03B1\u03BD\u03B5", -1, 1),
          new Among("\u03B1\u03B8\u03C1\u03BF", -1, 1),
          new Among("\u03C3\u03C5\u03BD\u03B1\u03B8\u03C1\u03BF", 7, 1)};

  private final static Among a_3[] = {new Among("\u03B2", -1, 1),
      new Among("\u03B2\u03B1\u03B8\u03C5\u03C1\u03B9", -1, 1),
      new Among("\u03B2\u03B1\u03C1\u03BA", -1, 1), new Among("\u03BC\u03B1\u03C1\u03BA", -1, 1),
      new Among("\u03BB", -1, 1), new Among("\u03BC", -1, 1),
      new Among("\u03BA\u03BF\u03C1\u03BD", -1, 1), new Among("\u03C0", -1, 1),
      new Among("\u03B9\u03BC\u03C0", 7, 1), new Among("\u03C1", -1, 1),
      new Among("\u03BC\u03B1\u03C1", 9, 1), new Among("\u03B1\u03BC\u03C0\u03B1\u03C1", 9, 1),
      new Among("\u03B3\u03BA\u03C1", 9, 1),
      new Among("\u03B2\u03BF\u03BB\u03B2\u03BF\u03C1", 9, 1),
      new Among("\u03B3\u03BB\u03C5\u03BA\u03BF\u03C1", 9, 1),
      new Among("\u03C0\u03B9\u03C0\u03B5\u03C1\u03BF\u03C1", 9, 1),
      new Among("\u03C0\u03C1", 9, 1), new Among("\u03BC\u03C0\u03C1", 16, 1),
      new Among("\u03B1\u03C1\u03C1", 9, 1),
      new Among("\u03B3\u03BB\u03C5\u03BA\u03C5\u03C1", 9, 1),
      new Among("\u03C0\u03BF\u03BB\u03C5\u03C1", 9, 1), new Among("\u03BB\u03BF\u03C5", -1, 1)};

  private final static Among a_4[] = {new Among("\u03B9\u03B6\u03B1", -1, 1),
      new Among("\u03B9\u03B6\u03B5", -1, 1), new Among("\u03B9\u03B6\u03B1\u03BC\u03B5", -1, 1),
      new Among("\u03B9\u03B6\u03BF\u03C5\u03BC\u03B5", -1, 1),
      new Among("\u03B9\u03B6\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03B9\u03B6\u03BF\u03C5\u03BD\u03B5", -1, 1),
      new Among("\u03B9\u03B6\u03B1\u03C4\u03B5", -1, 1),
      new Among("\u03B9\u03B6\u03B5\u03C4\u03B5", -1, 1),
      new Among("\u03B9\u03B6\u03B5\u03B9", -1, 1), new Among("\u03B9\u03B6\u03B1\u03BD", -1, 1),
      new Among("\u03B9\u03B6\u03BF\u03C5\u03BD", -1, 1),
      new Among("\u03B9\u03B6\u03B5\u03C3", -1, 1),
      new Among("\u03B9\u03B6\u03B5\u03B9\u03C3", -1, 1), new Among("\u03B9\u03B6\u03C9", -1, 1)};

  private final static Among a_5[] = {new Among("\u03B2\u03B9", -1, 1),
      new Among("\u03BB\u03B9", -1, 1), new Among("\u03B1\u03BB", -1, 1),
      new Among("\u03B5\u03BD", -1, 1), new Among("\u03C3", -1, 1), new Among("\u03C7", -1, 1),
      new Among("\u03C5\u03C8", -1, 1), new Among("\u03B6\u03C9", -1, 1)};

  private final static Among a_6[] = {new Among("\u03C9\u03B8\u03B7\u03BA\u03B1", -1, 1),
      new Among("\u03C9\u03B8\u03B7\u03BA\u03B5", -1, 1),
      new Among("\u03C9\u03B8\u03B7\u03BA\u03B1\u03BC\u03B5", -1, 1),
      new Among("\u03C9\u03B8\u03B7\u03BA\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03C9\u03B8\u03B7\u03BA\u03B1\u03C4\u03B5", -1, 1),
      new Among("\u03C9\u03B8\u03B7\u03BA\u03B1\u03BD", -1, 1),
      new Among("\u03C9\u03B8\u03B7\u03BA\u03B5\u03C3", -1, 1)};

  private final static Among a_7[] = {new Among("\u03BE\u03B1\u03BD\u03B1\u03C0\u03B1", -1, 1),
      new Among("\u03B5\u03C0\u03B1", -1, 1),
      new Among("\u03C0\u03B5\u03C1\u03B9\u03C0\u03B1", -1, 1),
      new Among("\u03B1\u03BD\u03B1\u03BC\u03C0\u03B1", -1, 1),
      new Among("\u03B5\u03BC\u03C0\u03B1", -1, 1),
      new Among("\u03C7\u03B1\u03C1\u03C4\u03BF\u03C0\u03B1", -1, 1),
      new Among("\u03B5\u03BE\u03B1\u03C1\u03C7\u03B1", -1, 1),
      new Among("\u03BA\u03BB\u03B5", -1, 1), new Among("\u03B5\u03BA\u03BB\u03B5", 7, 1),
      new Among("\u03B1\u03C0\u03B5\u03BA\u03BB\u03B5", 8, 1),
      new Among("\u03B1\u03C0\u03BF\u03BA\u03BB\u03B5", 7, 1),
      new Among("\u03B5\u03C3\u03C9\u03BA\u03BB\u03B5", 7, 1),
      new Among("\u03B4\u03B1\u03BD\u03B5", -1, 1), new Among("\u03C0\u03B5", -1, 1),
      new Among("\u03B5\u03C0\u03B5", 13, 1),
      new Among("\u03BC\u03B5\u03C4\u03B5\u03C0\u03B5", 14, 1),
      new Among("\u03B5\u03C3\u03B5", -1, 1), new Among("\u03B1\u03B8\u03C1\u03BF", -1, 1),
      new Among("\u03C3\u03C5\u03BD\u03B1\u03B8\u03C1\u03BF", 17, 1)};

  private final static Among a_8[] = {new Among("\u03B3\u03B5", -1, 1),
      new Among("\u03B3\u03BA\u03B5", -1, 1), new Among("\u03B3\u03BA", -1, 1),
      new Among("\u03BC", -1, 1), new Among("\u03C0\u03BF\u03C5\u03BA\u03B1\u03BC", 3, 1),
      new Among("\u03BA\u03BF\u03BC", 3, 1), new Among("\u03B1\u03BD", -1, 1),
      new Among("\u03BF\u03BB\u03BF", -1, 1), new Among("\u03C0", -1, 1),
      new Among("\u03BB\u03B1\u03C1", -1, 1),
      new Among("\u03B4\u03B7\u03BC\u03BF\u03BA\u03C1\u03B1\u03C4", -1, 1),
      new Among("\u03B1\u03C6", -1, 1),
      new Among("\u03B3\u03B9\u03B3\u03B1\u03BD\u03C4\u03BF\u03B1\u03C6", 11, 1)};

  private final static Among a_9[] = {new Among("\u03B9\u03C3\u03B1", -1, 1),
      new Among("\u03B9\u03C3\u03B1\u03BC\u03B5", -1, 1),
      new Among("\u03B9\u03C3\u03B1\u03BD\u03B5", -1, 1), new Among("\u03B9\u03C3\u03B5", -1, 1),
      new Among("\u03B9\u03C3\u03B1\u03C4\u03B5", -1, 1),
      new Among("\u03B9\u03C3\u03B1\u03BD", -1, 1), new Among("\u03B9\u03C3\u03B5\u03C3", -1, 1)};

  private final static Among a_10[] = {new Among("\u03BE\u03B1\u03BD\u03B1\u03C0\u03B1", -1, 1),
      new Among("\u03B5\u03C0\u03B1", -1, 1),
      new Among("\u03C0\u03B5\u03C1\u03B9\u03C0\u03B1", -1, 1),
      new Among("\u03B1\u03BD\u03B1\u03BC\u03C0\u03B1", -1, 1),
      new Among("\u03B5\u03BC\u03C0\u03B1", -1, 1),
      new Among("\u03C7\u03B1\u03C1\u03C4\u03BF\u03C0\u03B1", -1, 1),
      new Among("\u03B5\u03BE\u03B1\u03C1\u03C7\u03B1", -1, 1),
      new Among("\u03BA\u03BB\u03B5", -1, 1), new Among("\u03B5\u03BA\u03BB\u03B5", 7, 1),
      new Among("\u03B1\u03C0\u03B5\u03BA\u03BB\u03B5", 8, 1),
      new Among("\u03B1\u03C0\u03BF\u03BA\u03BB\u03B5", 7, 1),
      new Among("\u03B5\u03C3\u03C9\u03BA\u03BB\u03B5", 7, 1),
      new Among("\u03B4\u03B1\u03BD\u03B5", -1, 1), new Among("\u03C0\u03B5", -1, 1),
      new Among("\u03B5\u03C0\u03B5", 13, 1),
      new Among("\u03BC\u03B5\u03C4\u03B5\u03C0\u03B5", 14, 1),
      new Among("\u03B5\u03C3\u03B5", -1, 1), new Among("\u03B1\u03B8\u03C1\u03BF", -1, 1),
      new Among("\u03C3\u03C5\u03BD\u03B1\u03B8\u03C1\u03BF", 17, 1)};

  private final static Among a_11[] = {new Among("\u03B9\u03C3\u03BF\u03C5\u03BC\u03B5", -1, 1),
      new Among("\u03B9\u03C3\u03BF\u03C5\u03BD\u03B5", -1, 1),
      new Among("\u03B9\u03C3\u03B5\u03C4\u03B5", -1, 1),
      new Among("\u03B9\u03C3\u03B5\u03B9", -1, 1),
      new Among("\u03B9\u03C3\u03BF\u03C5\u03BD", -1, 1),
      new Among("\u03B9\u03C3\u03B5\u03B9\u03C3", -1, 1), new Among("\u03B9\u03C3\u03C9", -1, 1)};

  private final static Among a_12[] = {new Among("\u03BA\u03BB\u03B5", -1, 1),
      new Among("\u03B5\u03C3\u03C9\u03BA\u03BB\u03B5", 0, 1),
      new Among("\u03C0\u03BB\u03B5", -1, 1), new Among("\u03B4\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03C3\u03B5", -1, 1), new Among("\u03B1\u03C3\u03B5", 4, 1),
      new Among("\u03C3\u03C5\u03BD\u03B1\u03B8\u03C1\u03BF", -1, 1)};

  private final static Among a_13[] = {new Among("\u03B1\u03C4\u03B1", -1, 1),
      new Among("\u03C6\u03B1", -1, 1), new Among("\u03B7\u03C6\u03B1", 1, 1),
      new Among("\u03BC\u03B5\u03B3", -1, 1), new Among("\u03BB\u03C5\u03B3", -1, 1),
      new Among("\u03B7\u03B4", -1, 1), new Among("\u03BA\u03B1\u03B8", -1, 1),
      new Among("\u03B5\u03C7\u03B8", -1, 1), new Among("\u03BA\u03B1\u03BA", -1, 1),
      new Among("\u03BC\u03B1\u03BA", -1, 1), new Among("\u03C3\u03BA", -1, 1),
      new Among("\u03C6\u03B9\u03BB", -1, 1), new Among("\u03BA\u03C5\u03BB", -1, 1),
      new Among("\u03BC", -1, 1), new Among("\u03B3\u03B5\u03BC", 13, 1),
      new Among("\u03B1\u03C7\u03BD", -1, 1), new Among("\u03C0", -1, 1),
      new Among("\u03B1\u03C0", 16, 1), new Among("\u03B5\u03BC\u03C0", 16, 1),
      new Among("\u03B5\u03C5\u03C0", 16, 1), new Among("\u03B1\u03C1", -1, 1),
      new Among("\u03B1\u03BF\u03C1", -1, 1), new Among("\u03B3\u03C5\u03C1", -1, 1),
      new Among("\u03C7\u03C1", -1, 1), new Among("\u03C7\u03C9\u03C1", -1, 1),
      new Among("\u03BA\u03C4", -1, 1), new Among("\u03B1\u03BA\u03C4", 25, 1),
      new Among("\u03C7\u03C4", -1, 1), new Among("\u03B1\u03C7\u03C4", 27, 1),
      new Among("\u03C4\u03B1\u03C7", -1, 1), new Among("\u03C3\u03C7", -1, 1),
      new Among("\u03B1\u03C3\u03C7", 30, 1), new Among("\u03C5\u03C8", -1, 1)};

  private final static Among a_14[] = {new Among("\u03B9\u03C3\u03C4\u03B1", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03B5", -1, 1), new Among("\u03B9\u03C3\u03C4\u03B7", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03BF\u03B9", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03C9\u03BD", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03BF", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03B5\u03C3", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03B7\u03C3", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03BF\u03C3", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03BF\u03C5\u03C3", -1, 1),
      new Among("\u03B9\u03C3\u03C4\u03BF\u03C5", -1, 1)};

  private final static Among a_15[] = {new Among("\u03B5\u03B3\u03BA\u03BB\u03B5", -1, 1),
      new Among("\u03B1\u03C0\u03BF\u03BA\u03BB\u03B5", -1, 1), new Among("\u03C3\u03B5", -1, 1),
      new Among("\u03BC\u03B5\u03C4\u03B1\u03C3\u03B5", 2, 1),
      new Among("\u03BC\u03B9\u03BA\u03C1\u03BF\u03C3\u03B5", 2, 1)};

  private final static Among a_16[] = {new Among("\u03B4\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03B1\u03BD\u03C4\u03B9\u03B4\u03B1\u03BD\u03B5", 0, 1)};

  private final static Among a_17[] = {new Among("\u03B1\u03C4\u03BF\u03BC\u03B9\u03BA", -1, 2),
      new Among("\u03B5\u03B8\u03BD\u03B9\u03BA", -1, 4),
      new Among("\u03C4\u03BF\u03C0\u03B9\u03BA", -1, 7),
      new Among("\u03B5\u03BA\u03BB\u03B5\u03BA\u03C4\u03B9\u03BA", -1, 5),
      new Among("\u03C3\u03BA\u03B5\u03C0\u03C4\u03B9\u03BA", -1, 6),
      new Among("\u03B3\u03BD\u03C9\u03C3\u03C4\u03B9\u03BA", -1, 3),
      new Among("\u03B1\u03B3\u03BD\u03C9\u03C3\u03C4\u03B9\u03BA", 5, 1),
      new Among("\u03B1\u03BB\u03B5\u03BE\u03B1\u03BD\u03B4\u03C1\u03B9\u03BD", -1, 8),
      new Among("\u03B8\u03B5\u03B1\u03C4\u03C1\u03B9\u03BD", -1, 10),
      new Among("\u03B2\u03C5\u03B6\u03B1\u03BD\u03C4\u03B9\u03BD", -1, 9)};

  private final static Among a_18[] = {new Among("\u03B9\u03C3\u03BC\u03BF\u03B9", -1, 1),
      new Among("\u03B9\u03C3\u03BC\u03C9\u03BD", -1, 1),
      new Among("\u03B9\u03C3\u03BC\u03BF", -1, 1),
      new Among("\u03B9\u03C3\u03BC\u03BF\u03C3", -1, 1),
      new Among("\u03B9\u03C3\u03BC\u03BF\u03C5\u03C3", -1, 1),
      new Among("\u03B9\u03C3\u03BC\u03BF\u03C5", -1, 1)};

  private final static Among a_19[] = {new Among("\u03C3", -1, 1), new Among("\u03C7", -1, 1)};

  private final static Among a_20[] =
      {new Among("\u03BF\u03C5\u03B4\u03B1\u03BA\u03B9\u03B1", -1, 1),
          new Among("\u03B1\u03C1\u03B1\u03BA\u03B9\u03B1", -1, 1),
          new Among("\u03BF\u03C5\u03B4\u03B1\u03BA\u03B9", -1, 1),
          new Among("\u03B1\u03C1\u03B1\u03BA\u03B9", -1, 1)};

  private final static Among a_21[] = {new Among("\u03B2\u03B1\u03BC\u03B2", -1, 1),
      new Among("\u03C3\u03BB\u03BF\u03B2", -1, 1),
      new Among("\u03C4\u03C3\u03B5\u03C7\u03BF\u03C3\u03BB\u03BF\u03B2", 1, 1),
      new Among("\u03C4\u03B6", -1, 1), new Among("\u03BA", -1, 1),
      new Among("\u03BA\u03B1\u03C0\u03B1\u03BA", 4, 1), new Among("\u03C3\u03BF\u03BA", 4, 1),
      new Among("\u03C3\u03BA", 4, 1), new Among("\u03BC\u03B1\u03BB", -1, 1),
      new Among("\u03C0\u03BB", -1, 1), new Among("\u03BB\u03BF\u03C5\u03BB", -1, 1),
      new Among("\u03C6\u03C5\u03BB", -1, 1), new Among("\u03BA\u03B1\u03B9\u03BC", -1, 1),
      new Among("\u03BA\u03BB\u03B9\u03BC", -1, 1), new Among("\u03C6\u03B1\u03C1\u03BC", -1, 1),
      new Among("\u03C3\u03C0\u03B1\u03BD", -1, 1), new Among("\u03BA\u03BF\u03BD", -1, 1),
      new Among("\u03BA\u03B1\u03C4\u03C1\u03B1\u03C0", -1, 1), new Among("\u03C1", -1, 1),
      new Among("\u03B2\u03C1", 18, 1), new Among("\u03BB\u03B1\u03B2\u03C1", 19, 1),
      new Among("\u03B1\u03BC\u03B2\u03C1", 19, 1), new Among("\u03BC\u03B5\u03C1", 18, 1),
      new Among("\u03B1\u03BD\u03B8\u03C1", 18, 1), new Among("\u03BA\u03BF\u03C1", 18, 1),
      new Among("\u03C3", -1, 1), new Among("\u03BD\u03B1\u03B3\u03BA\u03B1\u03C3", 25, 1),
      new Among("\u03BC\u03BF\u03C5\u03C3\u03C4", -1, 1), new Among("\u03C1\u03C5", -1, 1),
      new Among("\u03C6", -1, 1), new Among("\u03C3\u03C6", 29, 1),
      new Among("\u03B1\u03BB\u03B9\u03C3\u03C6", 30, 1), new Among("\u03C7", -1, 1)};

  private final static Among a_22[] = {new Among("\u03B2", -1, 1),
      new Among("\u03BA\u03B1\u03C1\u03B4", -1, 1), new Among("\u03B6", -1, 1),
      new Among("\u03C3\u03BA", -1, 1), new Among("\u03B2\u03B1\u03BB", -1, 1),
      new Among("\u03B3\u03BB", -1, 1), new Among("\u03C4\u03C1\u03B9\u03C0\u03BF\u03BB", -1, 1),
      new Among("\u03B3\u03B9\u03B1\u03BD", -1, 1),
      new Among("\u03B7\u03B3\u03BF\u03C5\u03BC\u03B5\u03BD", -1, 1),
      new Among("\u03BA\u03BF\u03BD", -1, 1),
      new Among("\u03BC\u03B1\u03BA\u03C1\u03C5\u03BD", -1, 1), new Among("\u03C0", -1, 1),
      new Among("\u03C0\u03B1\u03C4\u03B5\u03C1", -1, 1), new Among("\u03C4\u03BF\u03C3", -1, 1),
      new Among("\u03BD\u03C5\u03C6", -1, 1)};

  private final static Among a_23[] = {new Among("\u03B1\u03BA\u03B9\u03B1", -1, 1),
      new Among("\u03B1\u03C1\u03B1\u03BA\u03B9\u03B1", 0, 1),
      new Among("\u03B9\u03C4\u03C3\u03B1", -1, 1), new Among("\u03B1\u03BA\u03B9", -1, 1),
      new Among("\u03B1\u03C1\u03B1\u03BA\u03B9", 3, 1),
      new Among("\u03B9\u03C4\u03C3\u03C9\u03BD", -1, 1),
      new Among("\u03B9\u03C4\u03C3\u03B1\u03C3", -1, 1),
      new Among("\u03B9\u03C4\u03C3\u03B5\u03C3", -1, 1)};

  private final static Among a_24[] =
      {new Among("\u03C8\u03B1\u03BB", -1, 1), new Among("\u03B1\u03B9\u03C6\u03BD", -1, 1),
          new Among("\u03BF\u03BB\u03BF", -1, 1), new Among("\u03B9\u03C1", -1, 1)};

  private final static Among a_25[] =
      {new Among("\u03B5", -1, 1), new Among("\u03C0\u03B1\u03B9\u03C7\u03BD", -1, 1)};

  private final static Among a_26[] = {new Among("\u03B9\u03B4\u03B9\u03B1", -1, 1),
      new Among("\u03B9\u03B4\u03B9\u03C9\u03BD", -1, 1),
      new Among("\u03B9\u03B4\u03B9\u03BF", -1, 1)};

  private final static Among a_27[] = {new Among("\u03B9\u03B2", -1, 1), new Among("\u03B4", -1, 1),
      new Among("\u03C6\u03C1\u03B1\u03B3\u03BA", -1, 1), new Among("\u03BB\u03C5\u03BA", -1, 1),
      new Among("\u03BF\u03B2\u03B5\u03BB", -1, 1), new Among("\u03BC\u03B7\u03BD", -1, 1),
      new Among("\u03C1", -1, 1)};

  private final static Among a_28[] =
      {new Among("\u03B9\u03C3\u03BA\u03B5", -1, 1), new Among("\u03B9\u03C3\u03BA\u03BF", -1, 1),
          new Among("\u03B9\u03C3\u03BA\u03BF\u03C3", -1, 1),
          new Among("\u03B9\u03C3\u03BA\u03BF\u03C5", -1, 1)};

  private final static Among a_29[] =
      {new Among("\u03B1\u03B4\u03C9\u03BD", -1, 1), new Among("\u03B1\u03B4\u03B5\u03C3", -1, 1)};

  private final static Among a_30[] = {new Among("\u03B3\u03B9\u03B1\u03B3\u03B9", -1, -1),
      new Among("\u03B8\u03B5\u03B9", -1, -1), new Among("\u03BF\u03BA", -1, -1),
      new Among("\u03BC\u03B1\u03BC", -1, -1), new Among("\u03BC\u03B1\u03BD", -1, -1),
      new Among("\u03BC\u03C0\u03B1\u03BC\u03C0", -1, -1),
      new Among("\u03C0\u03B5\u03B8\u03B5\u03C1", -1, -1),
      new Among("\u03C0\u03B1\u03C4\u03B5\u03C1", -1, -1), new Among("\u03BA\u03C5\u03C1", -1, -1),
      new Among("\u03BD\u03C4\u03B1\u03BD\u03C4", -1, -1)};

  private final static Among a_31[] =
      {new Among("\u03B5\u03B4\u03C9\u03BD", -1, 1), new Among("\u03B5\u03B4\u03B5\u03C3", -1, 1)};

  private final static Among a_32[] =
      {new Among("\u03BC\u03B9\u03BB", -1, 1), new Among("\u03B4\u03B1\u03C0", -1, 1),
          new Among("\u03B3\u03B7\u03C0", -1, 1), new Among("\u03B9\u03C0", -1, 1),
          new Among("\u03B5\u03BC\u03C0", -1, 1), new Among("\u03BF\u03C0", -1, 1),
          new Among("\u03BA\u03C1\u03B1\u03C3\u03C0", -1, 1), new Among("\u03C5\u03C0", -1, 1)};

  private final static Among a_33[] = {new Among("\u03BF\u03C5\u03B4\u03C9\u03BD", -1, 1),
      new Among("\u03BF\u03C5\u03B4\u03B5\u03C3", -1, 1)};

  private final static Among a_34[] = {new Among("\u03C4\u03C1\u03B1\u03B3", -1, 1),
      new Among("\u03C6\u03B5", -1, 1), new Among("\u03BA\u03B1\u03BB\u03B9\u03B1\u03BA", -1, 1),
      new Among("\u03B1\u03C1\u03BA", -1, 1), new Among("\u03C3\u03BA", -1, 1),
      new Among("\u03C0\u03B5\u03C4\u03B1\u03BB", -1, 1), new Among("\u03B2\u03B5\u03BB", -1, 1),
      new Among("\u03BB\u03BF\u03C5\u03BB", -1, 1), new Among("\u03C6\u03BB", -1, 1),
      new Among("\u03C7\u03BD", -1, 1), new Among("\u03C0\u03BB\u03B5\u03BE", -1, 1),
      new Among("\u03C3\u03C0", -1, 1), new Among("\u03C6\u03C1", -1, 1),
      new Among("\u03C3", -1, 1), new Among("\u03BB\u03B9\u03C7", -1, 1)};

  private final static Among a_35[] =
      {new Among("\u03B5\u03C9\u03BD", -1, 1), new Among("\u03B5\u03C9\u03C3", -1, 1)};

  private final static Among a_36[] = {new Among("\u03B4", -1, 1), new Among("\u03B9\u03B4", 0, 1),
      new Among("\u03B8", -1, 1), new Among("\u03B3\u03B1\u03BB", -1, 1),
      new Among("\u03B5\u03BB", -1, 1), new Among("\u03BD", -1, 1), new Among("\u03C0", -1, 1),
      new Among("\u03C0\u03B1\u03C1", -1, 1)};

  private final static Among a_37[] = {new Among("\u03B9\u03B1", -1, 1),
      new Among("\u03B9\u03C9\u03BD", -1, 1), new Among("\u03B9\u03BF\u03C5", -1, 1)};

  private final static Among a_38[] =
      {new Among("\u03B9\u03BA\u03B1", -1, 1), new Among("\u03B9\u03BA\u03C9\u03BD", -1, 1),
          new Among("\u03B9\u03BA\u03BF", -1, 1), new Among("\u03B9\u03BA\u03BF\u03C5", -1, 1)};

  private final static Among a_39[] = {new Among("\u03B1\u03B4", -1, 1),
      new Among("\u03C3\u03C5\u03BD\u03B1\u03B4", 0, 1),
      new Among("\u03BA\u03B1\u03C4\u03B1\u03B4", 0, 1),
      new Among("\u03B1\u03BD\u03C4\u03B9\u03B4", -1, 1), new Among("\u03B5\u03BD\u03B4", -1, 1),
      new Among("\u03C6\u03C5\u03BB\u03BF\u03B4", -1, 1),
      new Among("\u03C5\u03C0\u03BF\u03B4", -1, 1),
      new Among("\u03C0\u03C1\u03C9\u03C4\u03BF\u03B4", -1, 1),
      new Among("\u03B5\u03BE\u03C9\u03B4", -1, 1), new Among("\u03B7\u03B8", -1, 1),
      new Among("\u03B1\u03BD\u03B7\u03B8", 9, 1), new Among("\u03BE\u03B9\u03BA", -1, 1),
      new Among("\u03B1\u03BB", -1, 1),
      new Among("\u03B1\u03BC\u03BC\u03BF\u03C7\u03B1\u03BB", 12, 1),
      new Among("\u03C3\u03C5\u03BD\u03BF\u03BC\u03B7\u03BB", -1, 1),
      new Among("\u03BC\u03C0\u03BF\u03BB", -1, 1), new Among("\u03BC\u03BF\u03C5\u03BB", -1, 1),
      new Among("\u03C4\u03C3\u03B1\u03BC", -1, 1), new Among("\u03B2\u03C1\u03C9\u03BC", -1, 1),
      new Among("\u03B1\u03BC\u03B1\u03BD", -1, 1), new Among("\u03BC\u03C0\u03B1\u03BD", -1, 1),
      new Among("\u03BA\u03B1\u03BB\u03BB\u03B9\u03BD", -1, 1),
      new Among("\u03C0\u03BF\u03C3\u03C4\u03B5\u03BB\u03BD", -1, 1),
      new Among("\u03C6\u03B9\u03BB\u03BF\u03BD", -1, 1),
      new Among("\u03BA\u03B1\u03BB\u03C0", -1, 1), new Among("\u03B3\u03B5\u03C1", -1, 1),
      new Among("\u03C7\u03B1\u03C3", -1, 1), new Among("\u03BC\u03C0\u03BF\u03C3", -1, 1),
      new Among("\u03C0\u03BB\u03B9\u03B1\u03C4\u03C3", -1, 1),
      new Among("\u03C0\u03B5\u03C4\u03C3", -1, 1), new Among("\u03C0\u03B9\u03C4\u03C3", -1, 1),
      new Among("\u03C6\u03C5\u03C3", -1, 1),
      new Among("\u03BC\u03C0\u03B1\u03B3\u03B9\u03B1\u03C4", -1, 1),
      new Among("\u03BD\u03B9\u03C4", -1, 1),
      new Among("\u03C0\u03B9\u03BA\u03B1\u03BD\u03C4", -1, 1),
      new Among("\u03C3\u03B5\u03C1\u03C4", -1, 1)};

  private final static Among a_40[] = {new Among("\u03B1\u03B3\u03B1\u03BC\u03B5", -1, 1),
      new Among("\u03B7\u03BA\u03B1\u03BC\u03B5", -1, 1),
      new Among("\u03B7\u03B8\u03B7\u03BA\u03B1\u03BC\u03B5", 1, 1),
      new Among("\u03B7\u03C3\u03B1\u03BC\u03B5", -1, 1),
      new Among("\u03BF\u03C5\u03C3\u03B1\u03BC\u03B5", -1, 1)};

  private final static Among a_41[] = {new Among("\u03B2\u03BF\u03C5\u03B2", -1, 1),
      new Among("\u03BE\u03B5\u03B8", -1, 1), new Among("\u03C0\u03B5\u03B8", -1, 1),
      new Among("\u03B1\u03C0\u03BF\u03B8", -1, 1), new Among("\u03B1\u03C0\u03BF\u03BA", -1, 1),
      new Among("\u03BF\u03C5\u03BB", -1, 1), new Among("\u03B1\u03BD\u03B1\u03C0", -1, 1),
      new Among("\u03C0\u03B9\u03BA\u03C1", -1, 1), new Among("\u03C0\u03BF\u03C4", -1, 1),
      new Among("\u03B1\u03C0\u03BF\u03C3\u03C4", -1, 1), new Among("\u03C7", -1, 1),
      new Among("\u03C3\u03B9\u03C7", 10, 1)};

  private final static Among a_42[] =
      {new Among("\u03C4\u03C1", -1, 1), new Among("\u03C4\u03C3", -1, 1)};

  private final static Among a_43[] = {new Among("\u03B1\u03B3\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03B7\u03BA\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03B7\u03B8\u03B7\u03BA\u03B1\u03BD\u03B5", 1, 1),
      new Among("\u03B7\u03C3\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03BF\u03C5\u03C3\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03BF\u03BD\u03C4\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03B9\u03BF\u03BD\u03C4\u03B1\u03BD\u03B5", 5, 1),
      new Among("\u03BF\u03C5\u03BD\u03C4\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03B9\u03BF\u03C5\u03BD\u03C4\u03B1\u03BD\u03B5", 7, 1),
      new Among("\u03BF\u03C4\u03B1\u03BD\u03B5", -1, 1),
      new Among("\u03B9\u03BF\u03C4\u03B1\u03BD\u03B5", 9, 1)};

  private final static Among a_44[] = {new Among("\u03C4\u03B1\u03B2", -1, 1),
      new Among("\u03BD\u03C4\u03B1\u03B2", 0, 1),
      new Among("\u03C8\u03B7\u03BB\u03BF\u03C4\u03B1\u03B2", 0, 1),
      new Among("\u03BB\u03B9\u03B2", -1, 1), new Among("\u03BA\u03BB\u03B9\u03B2", 3, 1),
      new Among("\u03BE\u03B7\u03C1\u03BF\u03BA\u03BB\u03B9\u03B2", 4, 1),
      new Among("\u03B3", -1, 1), new Among("\u03B1\u03B3", 6, 1),
      new Among("\u03C4\u03C1\u03B1\u03B3", 7, 1), new Among("\u03C4\u03C3\u03B1\u03B3", 7, 1),
      new Among("\u03B1\u03B8\u03B9\u03B3\u03B3", 6, 1),
      new Among("\u03C4\u03C3\u03B9\u03B3\u03B3", 6, 1),
      new Among("\u03B1\u03C4\u03C3\u03B9\u03B3\u03B3", 11, 1),
      new Among("\u03C3\u03C4\u03B5\u03B3", 6, 1), new Among("\u03B1\u03C0\u03B7\u03B3", 6, 1),
      new Among("\u03C3\u03B9\u03B3", 6, 1), new Among("\u03B1\u03BD\u03BF\u03C1\u03B3", 6, 1),
      new Among("\u03B5\u03BD\u03BF\u03C1\u03B3", 6, 1),
      new Among("\u03BA\u03B1\u03BB\u03C0\u03BF\u03C5\u03B6", -1, 1), new Among("\u03B8", -1, 1),
      new Among("\u03BC\u03C9\u03B1\u03BC\u03B5\u03B8", 19, 1),
      new Among("\u03C0\u03B9\u03B8", 19, 1), new Among("\u03B1\u03C0\u03B9\u03B8", 21, 1),
      new Among("\u03B4\u03B5\u03BA", -1, 1), new Among("\u03C0\u03B5\u03BB\u03B5\u03BA", -1, 1),
      new Among("\u03B9\u03BA", -1, 1), new Among("\u03B1\u03BD\u03B9\u03BA", 25, 1),
      new Among("\u03B2\u03BF\u03C5\u03BB\u03BA", -1, 1),
      new Among("\u03B2\u03B1\u03C3\u03BA", -1, 1),
      new Among("\u03B2\u03C1\u03B1\u03C7\u03C5\u03BA", -1, 1),
      new Among("\u03B3\u03B1\u03BB", -1, 1),
      new Among("\u03BA\u03B1\u03C4\u03B1\u03B3\u03B1\u03BB", 30, 1),
      new Among("\u03BF\u03BB\u03BF\u03B3\u03B1\u03BB", 30, 1),
      new Among("\u03B2\u03B1\u03B8\u03C5\u03B3\u03B1\u03BB", 30, 1),
      new Among("\u03BC\u03B5\u03BB", -1, 1),
      new Among("\u03BA\u03B1\u03C3\u03C4\u03B5\u03BB", -1, 1),
      new Among("\u03C0\u03BF\u03C1\u03C4\u03BF\u03BB", -1, 1), new Among("\u03C0\u03BB", -1, 1),
      new Among("\u03B4\u03B9\u03C0\u03BB", 37, 1),
      new Among("\u03BB\u03B1\u03BF\u03C0\u03BB", 37, 1),
      new Among("\u03C8\u03C5\u03C7\u03BF\u03C0\u03BB", 37, 1),
      new Among("\u03BF\u03C5\u03BB", -1, 1), new Among("\u03BC", -1, 1),
      new Among("\u03BF\u03BB\u03B9\u03B3\u03BF\u03B4\u03B1\u03BC", 42, 1),
      new Among("\u03BC\u03BF\u03C5\u03C3\u03BF\u03C5\u03BB\u03BC", 42, 1),
      new Among("\u03B4\u03C1\u03B1\u03B4\u03BF\u03C5\u03BC", 42, 1),
      new Among("\u03B2\u03C1\u03B1\u03C7\u03BC", 42, 1), new Among("\u03BD", -1, 1),
      new Among("\u03B1\u03BC\u03B5\u03C1\u03B9\u03BA\u03B1\u03BD", 47, 1),
      new Among("\u03C0", -1, 1), new Among("\u03B1\u03B4\u03B1\u03C0", 49, 1),
      new Among("\u03C7\u03B1\u03BC\u03B7\u03BB\u03BF\u03B4\u03B1\u03C0", 49, 1),
      new Among("\u03C0\u03BF\u03BB\u03C5\u03B4\u03B1\u03C0", 49, 1),
      new Among("\u03BA\u03BF\u03C0", 49, 1),
      new Among("\u03C5\u03C0\u03BF\u03BA\u03BF\u03C0", 53, 1),
      new Among("\u03C4\u03C3\u03BF\u03C0", 49, 1), new Among("\u03C3\u03C0", 49, 1),
      new Among("\u03B5\u03C1", -1, 1), new Among("\u03B3\u03B5\u03C1", 57, 1),
      new Among("\u03B2\u03B5\u03C4\u03B5\u03C1", 57, 1),
      new Among("\u03BB\u03BF\u03C5\u03B8\u03B7\u03C1", -1, 1),
      new Among("\u03BA\u03BF\u03C1\u03BC\u03BF\u03C1", -1, 1),
      new Among("\u03C0\u03B5\u03C1\u03B9\u03C4\u03C1", -1, 1),
      new Among("\u03BF\u03C5\u03C1", -1, 1), new Among("\u03C3", -1, 1),
      new Among("\u03B2\u03B1\u03C3", 64, 1), new Among("\u03C0\u03BF\u03BB\u03B9\u03C3", 64, 1),
      new Among("\u03C3\u03B1\u03C1\u03B1\u03BA\u03B1\u03C4\u03C3", 64, 1),
      new Among("\u03B8\u03C5\u03C3", 64, 1), new Among("\u03B4\u03B9\u03B1\u03C4", -1, 1),
      new Among("\u03C0\u03BB\u03B1\u03C4", -1, 1),
      new Among("\u03C4\u03C3\u03B1\u03C1\u03BB\u03B1\u03C4", -1, 1),
      new Among("\u03C4\u03B5\u03C4", -1, 1),
      new Among("\u03C0\u03BF\u03C5\u03C1\u03B9\u03C4", -1, 1),
      new Among("\u03C3\u03BF\u03C5\u03BB\u03C4", -1, 1),
      new Among("\u03BC\u03B1\u03B9\u03BD\u03C4", -1, 1),
      new Among("\u03B6\u03C9\u03BD\u03C4", -1, 1), new Among("\u03BA\u03B1\u03C3\u03C4", -1, 1),
      new Among("\u03C6", -1, 1), new Among("\u03B4\u03B9\u03B1\u03C6", 78, 1),
      new Among("\u03C3\u03C4\u03B5\u03C6", 78, 1),
      new Among("\u03C6\u03C9\u03C4\u03BF\u03C3\u03C4\u03B5\u03C6", 80, 1),
      new Among("\u03C0\u03B5\u03C1\u03B7\u03C6", 78, 1),
      new Among("\u03C5\u03C0\u03B5\u03C1\u03B7\u03C6", 82, 1),
      new Among("\u03BA\u03BF\u03B9\u03BB\u03B1\u03C1\u03C6", 78, 1),
      new Among("\u03C0\u03B5\u03BD\u03C4\u03B1\u03C1\u03C6", 78, 1),
      new Among("\u03BF\u03C1\u03C6", 78, 1), new Among("\u03C7", -1, 1),
      new Among("\u03B1\u03BC\u03B7\u03C7", 87, 1),
      new Among("\u03B2\u03B9\u03BF\u03BC\u03B7\u03C7", 87, 1),
      new Among("\u03BC\u03B5\u03B3\u03BB\u03BF\u03B2\u03B9\u03BF\u03BC\u03B7\u03C7", 89, 1),
      new Among("\u03BA\u03B1\u03C0\u03BD\u03BF\u03B2\u03B9\u03BF\u03BC\u03B7\u03C7", 89, 1),
      new Among("\u03BC\u03B9\u03BA\u03C1\u03BF\u03B2\u03B9\u03BF\u03BC\u03B7\u03C7", 89, 1),
      new Among("\u03C0\u03BF\u03BB\u03C5\u03BC\u03B7\u03C7", 87, 1),
      new Among("\u03BB\u03B9\u03C7", 87, 1)};

  private final static Among a_45[] = {new Among("\u03B7\u03C3\u03B5\u03C4\u03B5", -1, 1)};

  private final static Among a_46[] = {new Among("\u03B5\u03BD\u03B4", -1, 1),
      new Among("\u03C3\u03C5\u03BD\u03B4", -1, 1), new Among("\u03BF\u03B4", -1, 1),
      new Among("\u03B4\u03B9\u03B1\u03B8", -1, 1), new Among("\u03BA\u03B1\u03B8", -1, 1),
      new Among("\u03C1\u03B1\u03B8", -1, 1), new Among("\u03C4\u03B1\u03B8", -1, 1),
      new Among("\u03C4\u03B9\u03B8", -1, 1), new Among("\u03B5\u03BA\u03B8", -1, 1),
      new Among("\u03B5\u03BD\u03B8", -1, 1), new Among("\u03C3\u03C5\u03BD\u03B8", -1, 1),
      new Among("\u03C1\u03BF\u03B8", -1, 1), new Among("\u03C5\u03C0\u03B5\u03C1\u03B8", -1, 1),
      new Among("\u03C3\u03B8", -1, 1), new Among("\u03B5\u03C5\u03B8", -1, 1),
      new Among("\u03B1\u03C1\u03BA", -1, 1), new Among("\u03C9\u03C6\u03B5\u03BB", -1, 1),
      new Among("\u03B2\u03BF\u03BB", -1, 1), new Among("\u03B1\u03B9\u03BD", -1, 1),
      new Among("\u03C0\u03BF\u03BD", -1, 1), new Among("\u03C1\u03BF\u03BD", -1, 1),
      new Among("\u03C3\u03C5\u03BD", -1, 1), new Among("\u03B2\u03B1\u03C1", -1, 1),
      new Among("\u03B2\u03C1", -1, 1), new Among("\u03B1\u03B9\u03C1", -1, 1),
      new Among("\u03C6\u03BF\u03C1", -1, 1), new Among("\u03B5\u03C5\u03C1", -1, 1),
      new Among("\u03C0\u03C5\u03C1", -1, 1), new Among("\u03C7\u03C9\u03C1", -1, 1),
      new Among("\u03BD\u03B5\u03C4", -1, 1), new Among("\u03C3\u03C7", -1, 1)};

  private final static Among a_47[] = {new Among("\u03C0\u03B1\u03B3", -1, 1),
      new Among("\u03B4", -1, 1), new Among("\u03B1\u03B4", 1, 1), new Among("\u03B8", -1, 1),
      new Among("\u03B1\u03B8", 3, 1), new Among("\u03C4\u03BF\u03BA", -1, 1),
      new Among("\u03C3\u03BA", -1, 1),
      new Among("\u03C0\u03B1\u03C1\u03B1\u03BA\u03B1\u03BB", -1, 1),
      new Among("\u03C3\u03BA\u03B5\u03BB", -1, 1), new Among("\u03B1\u03C0\u03BB", -1, 1),
      new Among("\u03B5\u03BC", -1, 1), new Among("\u03B1\u03BD", -1, 1),
      new Among("\u03B2\u03B5\u03BD", -1, 1), new Among("\u03B2\u03B1\u03C1\u03BF\u03BD", -1, 1),
      new Among("\u03BA\u03BF\u03C0", -1, 1), new Among("\u03C3\u03B5\u03C1\u03C0", -1, 1),
      new Among("\u03B1\u03B2\u03B1\u03C1", -1, 1), new Among("\u03B5\u03BD\u03B1\u03C1", -1, 1),
      new Among("\u03B1\u03B2\u03C1", -1, 1), new Among("\u03BC\u03C0\u03BF\u03C1", -1, 1),
      new Among("\u03B8\u03B1\u03C1\u03C1", -1, 1), new Among("\u03BD\u03C4\u03C1", -1, 1),
      new Among("\u03C5", -1, 1), new Among("\u03BD\u03B9\u03C6", -1, 1),
      new Among("\u03C3\u03C5\u03C1\u03C6", -1, 1)};

  private final static Among a_48[] = {new Among("\u03BF\u03BD\u03C4\u03B1\u03C3", -1, 1),
      new Among("\u03C9\u03BD\u03C4\u03B1\u03C3", -1, 1)};

  private final static Among a_49[] = {new Among("\u03BF\u03BC\u03B1\u03C3\u03C4\u03B5", -1, 1),
      new Among("\u03B9\u03BF\u03BC\u03B1\u03C3\u03C4\u03B5", 0, 1)};

  private final static Among a_50[] = {new Among("\u03C0", -1, 1), new Among("\u03B1\u03C0", 0, 1),
      new Among("\u03B1\u03BA\u03B1\u03C4\u03B1\u03C0", 1, 1),
      new Among("\u03C3\u03C5\u03BC\u03C0", 0, 1),
      new Among("\u03B1\u03C3\u03C5\u03BC\u03C0", 3, 1),
      new Among("\u03B1\u03BC\u03B5\u03C4\u03B1\u03BC\u03C6", -1, 1)};

  private final static Among a_51[] = {new Among("\u03B6", -1, 1), new Among("\u03B1\u03BB", -1, 1),
      new Among("\u03C0\u03B1\u03C1\u03B1\u03BA\u03B1\u03BB", 1, 1),
      new Among("\u03B5\u03BA\u03C4\u03B5\u03BB", -1, 1), new Among("\u03BC", -1, 1),
      new Among("\u03BE", -1, 1), new Among("\u03C0\u03C1\u03BF", -1, 1),
      new Among("\u03B1\u03C1", -1, 1), new Among("\u03BD\u03B9\u03C3", -1, 1)};

  private final static Among a_52[] = {new Among("\u03B7\u03B8\u03B7\u03BA\u03B1", -1, 1),
      new Among("\u03B7\u03B8\u03B7\u03BA\u03B5", -1, 1),
      new Among("\u03B7\u03B8\u03B7\u03BA\u03B5\u03C3", -1, 1)};

  private final static Among a_53[] = {new Among("\u03C0\u03B9\u03B8", -1, 1),
      new Among("\u03BF\u03B8", -1, 1), new Among("\u03BD\u03B1\u03C1\u03B8", -1, 1),
      new Among("\u03C3\u03BA\u03BF\u03C5\u03BB", -1, 1),
      new Among("\u03C3\u03BA\u03C9\u03BB", -1, 1), new Among("\u03C3\u03C6", -1, 1)};

  private final static Among a_54[] =
      {new Among("\u03B8", -1, 1), new Among("\u03B4\u03B9\u03B1\u03B8", 0, 1),
          new Among("\u03C0\u03B1\u03C1\u03B1\u03BA\u03B1\u03C4\u03B1\u03B8", 0, 1),
          new Among("\u03C3\u03C5\u03BD\u03B8", 0, 1),
          new Among("\u03C0\u03C1\u03BF\u03C3\u03B8", 0, 1)};

  private final static Among a_55[] = {new Among("\u03B7\u03BA\u03B1", -1, 1),
      new Among("\u03B7\u03BA\u03B5", -1, 1), new Among("\u03B7\u03BA\u03B5\u03C3", -1, 1)};

  private final static Among a_56[] = {new Among("\u03C6\u03B1\u03B3", -1, 1),
      new Among("\u03BB\u03B7\u03B3", -1, 1), new Among("\u03C6\u03C1\u03C5\u03B4", -1, 1),
      new Among("\u03BC\u03B1\u03BD\u03C4\u03B9\u03BB", -1, 1),
      new Among("\u03BC\u03B1\u03BB\u03BB", -1, 1), new Among("\u03BF\u03BC", -1, 1),
      new Among("\u03B2\u03BB\u03B5\u03C0", -1, 1),
      new Among("\u03C0\u03BF\u03B4\u03B1\u03C1", -1, 1),
      new Among("\u03BA\u03C5\u03BC\u03B1\u03C4", -1, 1),
      new Among("\u03C0\u03C1\u03C9\u03C4", -1, 1), new Among("\u03BB\u03B1\u03C7", -1, 1),
      new Among("\u03C0\u03B1\u03BD\u03C4\u03B1\u03C7", -1, 1)};

  private final static Among a_57[] = {new Among("\u03C4\u03C3\u03B1", -1, 1),
      new Among("\u03C7\u03B1\u03B4", -1, 1), new Among("\u03BC\u03B5\u03B4", -1, 1),
      new Among("\u03BB\u03B1\u03BC\u03C0\u03B9\u03B4", -1, 1), new Among("\u03B4\u03B5", -1, 1),
      new Among("\u03C0\u03BB\u03B5", -1, 1), new Among("\u03BC\u03B5\u03C3\u03B1\u03B6", -1, 1),
      new Among("\u03B4\u03B5\u03C3\u03C0\u03BF\u03B6", -1, 1),
      new Among("\u03B1\u03B9\u03B8", -1, 1),
      new Among("\u03C6\u03B1\u03C1\u03BC\u03B1\u03BA", -1, 1),
      new Among("\u03B1\u03B3\u03BA", -1, 1), new Among("\u03B1\u03BD\u03B7\u03BA", -1, 1),
      new Among("\u03BB", -1, 1), new Among("\u03BC", -1, 1), new Among("\u03B1\u03BC", 13, 1),
      new Among("\u03B2\u03C1\u03BF\u03BC", 13, 1),
      new Among("\u03C5\u03C0\u03BF\u03C4\u03B5\u03B9\u03BD", -1, 1),
      new Among("\u03B5\u03BA\u03BB\u03B9\u03C0", -1, 1), new Among("\u03C1", -1, 1),
      new Among("\u03B5\u03BD\u03B4\u03B9\u03B1\u03C6\u03B5\u03C1", 18, 1),
      new Among("\u03B1\u03BD\u03B1\u03C1\u03C1", 18, 1), new Among("\u03C0\u03B1\u03C4", -1, 1),
      new Among("\u03BA\u03B1\u03B8\u03B1\u03C1\u03B5\u03C5", -1, 1),
      new Among("\u03B4\u03B5\u03C5\u03C4\u03B5\u03C1\u03B5\u03C5", -1, 1),
      new Among("\u03BB\u03B5\u03C7", -1, 1)};

  private final static Among a_58[] =
      {new Among("\u03BF\u03C5\u03C3\u03B1", -1, 1), new Among("\u03BF\u03C5\u03C3\u03B5", -1, 1),
          new Among("\u03BF\u03C5\u03C3\u03B5\u03C3", -1, 1)};

  private final static Among a_59[] = {new Among("\u03C8\u03BF\u03C6", -1, -1),
      new Among("\u03BD\u03B1\u03C5\u03BB\u03BF\u03C7", -1, -1)};

  private final static Among a_60[] =
      {new Among("\u03C0\u03B5\u03BB", -1, 1), new Among("\u03BB\u03BB", -1, 1),
          new Among("\u03C3\u03BC\u03B7\u03BD", -1, 1), new Among("\u03C1\u03C0", -1, 1),
          new Among("\u03C0\u03C1", -1, 1), new Among("\u03C6\u03C1", -1, 1),
          new Among("\u03C7\u03BF\u03C1\u03C4", -1, 1), new Among("\u03BF\u03C6", -1, 1),
          new Among("\u03C3\u03C6", -1, 1), new Among("\u03BB\u03BF\u03C7", -1, 1)};

  private final static Among a_61[] = {new Among("\u03B1\u03BC\u03B1\u03BB\u03BB\u03B9", -1, 1),
      new Among("\u03BB", -1, 1), new Among("\u03B1\u03BC\u03B1\u03BB", 1, 1),
      new Among("\u03BC", -1, 1), new Among("\u03BF\u03C5\u03BB\u03B1\u03BC", 3, 1),
      new Among("\u03B5\u03BD", -1, 1), new Among("\u03B4\u03B5\u03C1\u03B2\u03B5\u03BD", 5, 1),
      new Among("\u03C0", -1, 1), new Among("\u03B1\u03B5\u03B9\u03C0", 7, 1),
      new Among("\u03B1\u03C1\u03C4\u03B9\u03C0", 7, 1),
      new Among("\u03C3\u03C5\u03BC\u03C0", 7, 1), new Among("\u03BD\u03B5\u03BF\u03C0", 7, 1),
      new Among("\u03BA\u03C1\u03BF\u03BA\u03B1\u03BB\u03BF\u03C0", 7, 1),
      new Among("\u03BF\u03BB\u03BF\u03C0", 7, 1),
      new Among("\u03C0\u03C1\u03BF\u03C3\u03C9\u03C0\u03BF\u03C0", 7, 1),
      new Among("\u03C3\u03B9\u03B4\u03B7\u03C1\u03BF\u03C0", 7, 1),
      new Among("\u03B4\u03C1\u03BF\u03C3\u03BF\u03C0", 7, 1),
      new Among("\u03B1\u03C3\u03C0", 7, 1), new Among("\u03B1\u03BD\u03C5\u03C0", 7, 1),
      new Among("\u03C1", -1, 1), new Among("\u03B1\u03C3\u03C0\u03B1\u03C1", 19, 1),
      new Among("\u03C7\u03B1\u03C1", 19, 1), new Among("\u03B1\u03C7\u03B1\u03C1", 21, 1),
      new Among("\u03B1\u03C0\u03B5\u03C1", 19, 1), new Among("\u03C4\u03C1", 19, 1),
      new Among("\u03BF\u03C5\u03C1", 19, 1), new Among("\u03C4", -1, 1),
      new Among("\u03B4\u03B9\u03B1\u03C4", 26, 1), new Among("\u03B5\u03C0\u03B9\u03C4", 26, 1),
      new Among("\u03C3\u03C5\u03BD\u03C4", 26, 1), new Among("\u03BF\u03BC\u03BF\u03C4", 26, 1),
      new Among("\u03BD\u03BF\u03BC\u03BF\u03C4", 30, 1),
      new Among("\u03B1\u03C0\u03BF\u03C4", 26, 1), new Among("\u03C5\u03C0\u03BF\u03C4", 26, 1),
      new Among("\u03B1\u03B2\u03B1\u03C3\u03C4", 26, 1),
      new Among("\u03B1\u03B9\u03BC\u03BF\u03C3\u03C4", 26, 1),
      new Among("\u03C0\u03C1\u03BF\u03C3\u03C4", 26, 1),
      new Among("\u03B1\u03BD\u03C5\u03C3\u03C4", 26, 1), new Among("\u03BD\u03B1\u03C5", -1, 1),
      new Among("\u03B1\u03C6", -1, 1), new Among("\u03BE\u03B5\u03C6", -1, 1),
      new Among("\u03B1\u03B4\u03B7\u03C6", -1, 1), new Among("\u03C0\u03B1\u03BC\u03C6", -1, 1),
      new Among("\u03C0\u03BF\u03BB\u03C5\u03C6", -1, 1)};

  private final static Among a_62[] = {new Among("\u03B1\u03B3\u03B1", -1, 1),
      new Among("\u03B1\u03B3\u03B5", -1, 1), new Among("\u03B1\u03B3\u03B5\u03C3", -1, 1)};

  private final static Among a_63[] = {new Among("\u03B7\u03C3\u03B1", -1, 1),
      new Among("\u03B7\u03C3\u03B5", -1, 1), new Among("\u03B7\u03C3\u03BF\u03C5", -1, 1)};

  private final static Among a_64[] =
      {new Among("\u03BD", -1, 1), new Among("\u03B4\u03C9\u03B4\u03B5\u03BA\u03B1\u03BD", 0, 1),
          new Among("\u03B5\u03C0\u03C4\u03B1\u03BD", 0, 1),
          new Among("\u03BC\u03B5\u03B3\u03B1\u03BB\u03BF\u03BD", 0, 1),
          new Among("\u03B5\u03C1\u03B7\u03BC\u03BF\u03BD", 0, 1),
          new Among("\u03C7\u03B5\u03C1\u03C3\u03BF\u03BD", 0, 1)};

  private final static Among a_65[] = {new Among("\u03B7\u03C3\u03C4\u03B5", -1, 1)};

  private final static Among a_66[] = {new Among("\u03C3\u03B2", -1, 1),
      new Among("\u03B1\u03C3\u03B2", 0, 1), new Among("\u03B1\u03C0\u03BB", -1, 1),
      new Among("\u03B1\u03B5\u03B9\u03BC\u03BD", -1, 1), new Among("\u03C7\u03C1", -1, 1),
      new Among("\u03B1\u03C7\u03C1", 4, 1),
      new Among("\u03BA\u03BF\u03B9\u03BD\u03BF\u03C7\u03C1", 4, 1),
      new Among("\u03B4\u03C5\u03C3\u03C7\u03C1", 4, 1),
      new Among("\u03B5\u03C5\u03C7\u03C1", 4, 1),
      new Among("\u03C0\u03B1\u03BB\u03B9\u03BC\u03C8", -1, 1)};

  private final static Among a_67[] = {new Among("\u03BF\u03C5\u03BD\u03B5", -1, 1),
      new Among("\u03B7\u03B8\u03BF\u03C5\u03BD\u03B5", 0, 1),
      new Among("\u03B7\u03C3\u03BF\u03C5\u03BD\u03B5", 0, 1)};

  private final static Among a_68[] =
      {new Among("\u03C3\u03C0\u03B9", -1, 1), new Among("\u03BD", -1, 1),
          new Among("\u03B5\u03BE\u03C9\u03BD", 1, 1), new Among("\u03C1", -1, 1),
          new Among("\u03C3\u03C4\u03C1\u03B1\u03B2\u03BF\u03BC\u03BF\u03C5\u03C4\u03C3", -1, 1),
          new Among("\u03BA\u03B1\u03BA\u03BF\u03BC\u03BF\u03C5\u03C4\u03C3", -1, 1)};

  private final static Among a_69[] = {new Among("\u03BF\u03C5\u03BC\u03B5", -1, 1),
      new Among("\u03B7\u03B8\u03BF\u03C5\u03BC\u03B5", 0, 1),
      new Among("\u03B7\u03C3\u03BF\u03C5\u03BC\u03B5", 0, 1)};

  private final static Among a_70[] =
      {new Among("\u03B1\u03B6", -1, 1), new Among("\u03C9\u03C1\u03B9\u03BF\u03C0\u03BB", -1, 1),
          new Among("\u03B1\u03C3\u03BF\u03C5\u03C3", -1, 1),
          new Among("\u03C0\u03B1\u03C1\u03B1\u03C3\u03BF\u03C5\u03C3", 2, 1),
          new Among("\u03B1\u03BB\u03BB\u03BF\u03C3\u03BF\u03C5\u03C3", -1, 1),
          new Among("\u03C6", -1, 1), new Among("\u03C7", -1, 1)};

  private final static Among a_71[] = {new Among("\u03BC\u03B1\u03C4\u03B1", -1, 1),
      new Among("\u03BC\u03B1\u03C4\u03C9\u03BD", -1, 1),
      new Among("\u03BC\u03B1\u03C4\u03BF\u03C3", -1, 1)};

  private final static Among a_72[] = {new Among("\u03B1", -1, 1),
      new Among("\u03B9\u03BF\u03C5\u03BC\u03B1", 0, 1),
      new Among("\u03BF\u03BC\u03BF\u03C5\u03BD\u03B1", 0, 1),
      new Among("\u03B9\u03BF\u03BC\u03BF\u03C5\u03BD\u03B1", 2, 1),
      new Among("\u03BF\u03C3\u03BF\u03C5\u03BD\u03B1", 0, 1),
      new Among("\u03B9\u03BF\u03C3\u03BF\u03C5\u03BD\u03B1", 4, 1), new Among("\u03B5", -1, 1),
      new Among("\u03B1\u03B3\u03B1\u03C4\u03B5", 6, 1),
      new Among("\u03B7\u03BA\u03B1\u03C4\u03B5", 6, 1),
      new Among("\u03B7\u03B8\u03B7\u03BA\u03B1\u03C4\u03B5", 8, 1),
      new Among("\u03B7\u03C3\u03B1\u03C4\u03B5", 6, 1),
      new Among("\u03BF\u03C5\u03C3\u03B1\u03C4\u03B5", 6, 1),
      new Among("\u03B5\u03B9\u03C4\u03B5", 6, 1),
      new Among("\u03B7\u03B8\u03B5\u03B9\u03C4\u03B5", 12, 1),
      new Among("\u03B9\u03B5\u03BC\u03B1\u03C3\u03C4\u03B5", 6, 1),
      new Among("\u03BF\u03C5\u03BC\u03B1\u03C3\u03C4\u03B5", 6, 1),
      new Among("\u03B9\u03BF\u03C5\u03BC\u03B1\u03C3\u03C4\u03B5", 15, 1),
      new Among("\u03B9\u03B5\u03C3\u03B1\u03C3\u03C4\u03B5", 6, 1),
      new Among("\u03BF\u03C3\u03B1\u03C3\u03C4\u03B5", 6, 1),
      new Among("\u03B9\u03BF\u03C3\u03B1\u03C3\u03C4\u03B5", 18, 1), new Among("\u03B7", -1, 1),
      new Among("\u03B9", -1, 1), new Among("\u03B1\u03BC\u03B1\u03B9", 21, 1),
      new Among("\u03B9\u03B5\u03BC\u03B1\u03B9", 21, 1),
      new Among("\u03BF\u03BC\u03B1\u03B9", 21, 1),
      new Among("\u03BF\u03C5\u03BC\u03B1\u03B9", 21, 1),
      new Among("\u03B1\u03C3\u03B1\u03B9", 21, 1), new Among("\u03B5\u03C3\u03B1\u03B9", 21, 1),
      new Among("\u03B9\u03B5\u03C3\u03B1\u03B9", 27, 1),
      new Among("\u03B1\u03C4\u03B1\u03B9", 21, 1), new Among("\u03B5\u03C4\u03B1\u03B9", 21, 1),
      new Among("\u03B9\u03B5\u03C4\u03B1\u03B9", 30, 1),
      new Among("\u03BF\u03BD\u03C4\u03B1\u03B9", 21, 1),
      new Among("\u03BF\u03C5\u03BD\u03C4\u03B1\u03B9", 21, 1),
      new Among("\u03B9\u03BF\u03C5\u03BD\u03C4\u03B1\u03B9", 33, 1),
      new Among("\u03B5\u03B9", 21, 1), new Among("\u03B1\u03B5\u03B9", 35, 1),
      new Among("\u03B7\u03B8\u03B5\u03B9", 35, 1), new Among("\u03B7\u03C3\u03B5\u03B9", 35, 1),
      new Among("\u03BF\u03B9", 21, 1), new Among("\u03B1\u03BD", -1, 1),
      new Among("\u03B1\u03B3\u03B1\u03BD", 40, 1), new Among("\u03B7\u03BA\u03B1\u03BD", 40, 1),
      new Among("\u03B7\u03B8\u03B7\u03BA\u03B1\u03BD", 42, 1),
      new Among("\u03B7\u03C3\u03B1\u03BD", 40, 1),
      new Among("\u03BF\u03C5\u03C3\u03B1\u03BD", 40, 1),
      new Among("\u03BF\u03BD\u03C4\u03BF\u03C5\u03C3\u03B1\u03BD", 45, 1),
      new Among("\u03B9\u03BF\u03BD\u03C4\u03BF\u03C5\u03C3\u03B1\u03BD", 46, 1),
      new Among("\u03BF\u03BD\u03C4\u03B1\u03BD", 40, 1),
      new Among("\u03B9\u03BF\u03BD\u03C4\u03B1\u03BD", 48, 1),
      new Among("\u03BF\u03C5\u03BD\u03C4\u03B1\u03BD", 40, 1),
      new Among("\u03B9\u03BF\u03C5\u03BD\u03C4\u03B1\u03BD", 50, 1),
      new Among("\u03BF\u03C4\u03B1\u03BD", 40, 1),
      new Among("\u03B9\u03BF\u03C4\u03B1\u03BD", 52, 1),
      new Among("\u03BF\u03BC\u03B1\u03C3\u03C4\u03B1\u03BD", 40, 1),
      new Among("\u03B9\u03BF\u03BC\u03B1\u03C3\u03C4\u03B1\u03BD", 54, 1),
      new Among("\u03BF\u03C3\u03B1\u03C3\u03C4\u03B1\u03BD", 40, 1),
      new Among("\u03B9\u03BF\u03C3\u03B1\u03C3\u03C4\u03B1\u03BD", 56, 1),
      new Among("\u03BF\u03C5\u03BD", -1, 1), new Among("\u03B7\u03B8\u03BF\u03C5\u03BD", 58, 1),
      new Among("\u03BF\u03BC\u03BF\u03C5\u03BD", 58, 1),
      new Among("\u03B9\u03BF\u03BC\u03BF\u03C5\u03BD", 60, 1),
      new Among("\u03B7\u03C3\u03BF\u03C5\u03BD", 58, 1),
      new Among("\u03BF\u03C3\u03BF\u03C5\u03BD", 58, 1),
      new Among("\u03B9\u03BF\u03C3\u03BF\u03C5\u03BD", 63, 1), new Among("\u03C9\u03BD", -1, 1),
      new Among("\u03B7\u03B4\u03C9\u03BD", 65, 1), new Among("\u03BF", -1, 1),
      new Among("\u03B1\u03C3", -1, 1), new Among("\u03B5\u03C3", -1, 1),
      new Among("\u03B7\u03B4\u03B5\u03C3", 69, 1), new Among("\u03B7\u03C3\u03B5\u03C3", 69, 1),
      new Among("\u03B7\u03C3", -1, 1), new Among("\u03B5\u03B9\u03C3", -1, 1),
      new Among("\u03B7\u03B8\u03B5\u03B9\u03C3", 73, 1), new Among("\u03BF\u03C3", -1, 1),
      new Among("\u03C5\u03C3", -1, 1), new Among("\u03BF\u03C5\u03C3", 76, 1),
      new Among("\u03C5", -1, 1), new Among("\u03BF\u03C5", 78, 1), new Among("\u03C9", -1, 1),
      new Among("\u03B1\u03C9", 80, 1), new Among("\u03B7\u03B8\u03C9", 80, 1),
      new Among("\u03B7\u03C3\u03C9", 80, 1)};

  private final static Among a_73[] = {new Among("\u03BF\u03C4\u03B5\u03C1", -1, 1),
      new Among("\u03B5\u03C3\u03C4\u03B5\u03C1", -1, 1),
      new Among("\u03C5\u03C4\u03B5\u03C1", -1, 1), new Among("\u03C9\u03C4\u03B5\u03C1", -1, 1),
      new Among("\u03BF\u03C4\u03B1\u03C4", -1, 1),
      new Among("\u03B5\u03C3\u03C4\u03B1\u03C4", -1, 1),
      new Among("\u03C5\u03C4\u03B1\u03C4", -1, 1), new Among("\u03C9\u03C4\u03B1\u03C4", -1, 1)};

  private static final char g_v[] = {81, 65, 16, 1};

  private static final char g_v2[] = {81, 65, 0, 1};

  private boolean B_test1;


  private boolean r_has_min_length() {
    // (, line 108
    if (!(current.length() >= 3)) {
      return false;
    }
    return true;
  }

  private boolean r_tolower() {
    int among_var;
    // (, line 112
    // repeat, line 113
    while (true) {
      int v_1 = limit - cursor;
      lab0: {
        // (, line 113
        // [, line 114
        ket = cursor;
        // substring, line 114
        among_var = find_among_b(a_0);
        if (among_var == 0) {
          break lab0;
        }
        // ], line 114
        bra = cursor;
        switch (among_var) {
          case 1:
            // (, line 115
            // <-, line 115
            slice_from("\u03B1");
            break;
          case 2:
            // (, line 116
            // <-, line 116
            slice_from("\u03B2");
            break;
          case 3:
            // (, line 117
            // <-, line 117
            slice_from("\u03B3");
            break;
          case 4:
            // (, line 118
            // <-, line 118
            slice_from("\u03B4");
            break;
          case 5:
            // (, line 119
            // <-, line 119
            slice_from("\u03B5");
            break;
          case 6:
            // (, line 120
            // <-, line 120
            slice_from("\u03B6");
            break;
          case 7:
            // (, line 121
            // <-, line 121
            slice_from("\u03B7");
            break;
          case 8:
            // (, line 122
            // <-, line 122
            slice_from("\u03B8");
            break;
          case 9:
            // (, line 123
            // <-, line 123
            slice_from("\u03B9");
            break;
          case 10:
            // (, line 124
            // <-, line 124
            slice_from("\u03BA");
            break;
          case 11:
            // (, line 125
            // <-, line 125
            slice_from("\u03BB");
            break;
          case 12:
            // (, line 126
            // <-, line 126
            slice_from("\u03BC");
            break;
          case 13:
            // (, line 127
            // <-, line 127
            slice_from("\u03BD");
            break;
          case 14:
            // (, line 128
            // <-, line 128
            slice_from("\u03BE");
            break;
          case 15:
            // (, line 129
            // <-, line 129
            slice_from("\u03BF");
            break;
          case 16:
            // (, line 130
            // <-, line 130
            slice_from("\u03C0");
            break;
          case 17:
            // (, line 131
            // <-, line 131
            slice_from("\u03C1");
            break;
          case 18:
            // (, line 132
            // <-, line 132
            slice_from("\u03C3");
            break;
          case 19:
            // (, line 133
            // <-, line 133
            slice_from("\u03C4");
            break;
          case 20:
            // (, line 134
            // <-, line 134
            slice_from("\u03C5");
            break;
          case 21:
            // (, line 135
            // <-, line 135
            slice_from("\u03C6");
            break;
          case 22:
            // (, line 136
            // <-, line 136
            slice_from("\u03C7");
            break;
          case 23:
            // (, line 137
            // <-, line 137
            slice_from("\u03C8");
            break;
          case 24:
            // (, line 138
            // <-, line 138
            slice_from("\u03C9");
            break;
          case 25:
            // (, line 160
            // next, line 160
            if (cursor <= limit_backward) {
              break lab0;
            }
            cursor--;
            break;
        }
        continue;
      }
      cursor = limit - v_1;
      break;
    }
    return true;
  }

  private boolean r_step1() {
    int among_var;
    // (, line 165
    // [, line 166
    ket = cursor;
    // substring, line 166
    among_var = find_among_b(a_1);
    if (among_var == 0) {
      return false;
    }
    // ], line 166
    bra = cursor;
    switch (among_var) {
      case 1:
        // (, line 167
        // <-, line 167
        slice_from("\u03C6\u03B1");
        break;
      case 2:
        // (, line 168
        // <-, line 168
        slice_from("\u03C3\u03BA\u03B1");
        break;
      case 3:
        // (, line 169
        // <-, line 169
        slice_from("\u03BF\u03BB\u03BF");
        break;
      case 4:
        // (, line 170
        // <-, line 170
        slice_from("\u03C3\u03BF");
        break;
      case 5:
        // (, line 171
        // <-, line 171
        slice_from("\u03C4\u03B1\u03C4\u03BF");
        break;
      case 6:
        // (, line 172
        // <-, line 172
        slice_from("\u03BA\u03C1\u03B5");
        break;
      case 7:
        // (, line 173
        // <-, line 173
        slice_from("\u03C0\u03B5\u03C1");
        break;
      case 8:
        // (, line 174
        // <-, line 174
        slice_from("\u03C4\u03B5\u03C1");
        break;
      case 9:
        // (, line 175
        // <-, line 175
        slice_from("\u03C6\u03C9");
        break;
      case 10:
        // (, line 176
        // <-, line 176
        slice_from("\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4");
        break;
      case 11:
        // (, line 177
        // <-, line 177
        slice_from("\u03B3\u03B5\u03B3\u03BF\u03BD");
        break;
    }
    // unset test1, line 179
    B_test1 = false;
    return true;
  }

  private boolean r_steps1() {
    // (, line 182
    // [, line 183
    ket = cursor;
    // substring, line 183
    if (find_among_b(a_4) == 0) {
      return false;
    }
    // ], line 183
    bra = cursor;
    // (, line 185
    // delete, line 186
    slice_del();
    // unset test1, line 187
    B_test1 = false;
    // or, line 191
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 188
        // [, line 188
        ket = cursor;
        // ], line 188
        bra = cursor;
        // substring, line 188
        if (find_among_b(a_2) == 0) {
          break lab1;
        }
        // atlimit, line 188
        if (cursor > limit_backward) {
          break lab1;
        }
        // (, line 190
        // <-, line 190
        slice_from("\u03B9");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 192
      // [, line 192
      ket = cursor;
      // ], line 192
      bra = cursor;
      // substring, line 192
      if (find_among_b(a_3) == 0) {
        return false;
      }
      // atlimit, line 192
      if (cursor > limit_backward) {
        return false;
      }
      // (, line 196
      // <-, line 196
      slice_from("\u03B9\u03B6");
    }
    return true;
  }

  private boolean r_steps2() {
    // (, line 202
    // [, line 203
    ket = cursor;
    // substring, line 203
    if (find_among_b(a_6) == 0) {
      return false;
    }
    // ], line 203
    bra = cursor;
    // (, line 204
    // delete, line 205
    slice_del();
    // unset test1, line 206
    B_test1 = false;
    // [, line 207
    ket = cursor;
    // ], line 207
    bra = cursor;
    // substring, line 207
    if (find_among_b(a_5) == 0) {
      return false;
    }
    // atlimit, line 207
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 208
    // <-, line 208
    slice_from("\u03C9\u03BD");
    return true;
  }

  private boolean r_steps3() {
    // (, line 214
    // [, line 215
    ket = cursor;
    // substring, line 215
    if (find_among_b(a_9) == 0) {
      return false;
    }
    // ], line 215
    bra = cursor;
    // (, line 216
    // delete, line 217
    slice_del();
    // unset test1, line 218
    B_test1 = false;
    // or, line 219
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 219
        // literal, line 219
        if (!(eq_s_b("\u03B9\u03C3\u03B1"))) {
          break lab1;
        }
        // atlimit, line 219
        if (cursor > limit_backward) {
          break lab1;
        }
        // <-, line 219
        slice_from("\u03B9\u03C3");
        break lab0;
      }
      cursor = limit - v_1;
      lab2: {
        // (, line 220
        // [, line 220
        ket = cursor;
        // ], line 220
        bra = cursor;
        // substring, line 220
        if (find_among_b(a_7) == 0) {
          break lab2;
        }
        // atlimit, line 220
        if (cursor > limit_backward) {
          break lab2;
        }
        // (, line 224
        // <-, line 224
        slice_from("\u03B9");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 226
      // [, line 226
      ket = cursor;
      // ], line 226
      bra = cursor;
      // substring, line 226
      if (find_among_b(a_8) == 0) {
        return false;
      }
      // atlimit, line 226
      if (cursor > limit_backward) {
        return false;
      }
      // (, line 229
      // <-, line 229
      slice_from("\u03B9\u03C3");
    }
    return true;
  }

  private boolean r_steps4() {
    // (, line 235
    // [, line 236
    ket = cursor;
    // substring, line 236
    if (find_among_b(a_11) == 0) {
      return false;
    }
    // ], line 236
    bra = cursor;
    // (, line 237
    // delete, line 238
    slice_del();
    // unset test1, line 239
    B_test1 = false;
    // [, line 240
    ket = cursor;
    // ], line 240
    bra = cursor;
    // substring, line 240
    if (find_among_b(a_10) == 0) {
      return false;
    }
    // atlimit, line 240
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 244
    // <-, line 244
    slice_from("\u03B9");
    return true;
  }

  private boolean r_steps5() {
    // (, line 250
    // [, line 251
    ket = cursor;
    // substring, line 251
    if (find_among_b(a_14) == 0) {
      return false;
    }
    // ], line 251
    bra = cursor;
    // (, line 253
    // delete, line 254
    slice_del();
    // unset test1, line 255
    B_test1 = false;
    // or, line 259
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 256
        // [, line 256
        ket = cursor;
        // ], line 256
        bra = cursor;
        // substring, line 256
        if (find_among_b(a_12) == 0) {
          break lab1;
        }
        // atlimit, line 256
        if (cursor > limit_backward) {
          break lab1;
        }
        // (, line 258
        // <-, line 258
        slice_from("\u03B9");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 260
      // [, line 260
      ket = cursor;
      // ], line 260
      bra = cursor;
      // substring, line 260
      if (find_among_b(a_13) == 0) {
        return false;
      }
      // atlimit, line 260
      if (cursor > limit_backward) {
        return false;
      }
      // (, line 264
      // <-, line 264
      slice_from("\u03B9\u03C3\u03C4");
    }
    return true;
  }

  private boolean r_steps6() {
    int among_var;
    // (, line 270
    // [, line 271
    ket = cursor;
    // substring, line 271
    if (find_among_b(a_18) == 0) {
      return false;
    }
    // ], line 271
    bra = cursor;
    // (, line 272
    // delete, line 273
    slice_del();
    // unset test1, line 274
    B_test1 = false;
    // or, line 278
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 275
        // [, line 275
        ket = cursor;
        // ], line 275
        bra = cursor;
        // substring, line 275
        if (find_among_b(a_15) == 0) {
          break lab1;
        }
        // atlimit, line 275
        if (cursor > limit_backward) {
          break lab1;
        }
        // (, line 277
        // <-, line 277
        slice_from("\u03B9\u03C3\u03BC");
        break lab0;
      }
      cursor = limit - v_1;
      lab2: {
        // (, line 279
        // [, line 279
        ket = cursor;
        // ], line 279
        bra = cursor;
        // substring, line 279
        if (find_among_b(a_16) == 0) {
          break lab2;
        }
        // atlimit, line 279
        if (cursor > limit_backward) {
          break lab2;
        }
        // (, line 281
        // <-, line 281
        slice_from("\u03B9");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 283
      // [, line 283
      ket = cursor;
      // substring, line 283
      among_var = find_among_b(a_17);
      if (among_var == 0) {
        return false;
      }
      // ], line 283
      bra = cursor;
      switch (among_var) {
        case 1:
          // (, line 284
          // <-, line 284
          slice_from("\u03B1\u03B3\u03BD\u03C9\u03C3\u03C4");
          break;
        case 2:
          // (, line 285
          // <-, line 285
          slice_from("\u03B1\u03C4\u03BF\u03BC");
          break;
        case 3:
          // (, line 286
          // <-, line 286
          slice_from("\u03B3\u03BD\u03C9\u03C3\u03C4");
          break;
        case 4:
          // (, line 287
          // <-, line 287
          slice_from("\u03B5\u03B8\u03BD");
          break;
        case 5:
          // (, line 288
          // <-, line 288
          slice_from("\u03B5\u03BA\u03BB\u03B5\u03BA\u03C4");
          break;
        case 6:
          // (, line 289
          // <-, line 289
          slice_from("\u03C3\u03BA\u03B5\u03C0\u03C4");
          break;
        case 7:
          // (, line 290
          // <-, line 290
          slice_from("\u03C4\u03BF\u03C0");
          break;
        case 8:
          // (, line 291
          // <-, line 291
          slice_from("\u03B1\u03BB\u03B5\u03BE\u03B1\u03BD\u03B4\u03C1");
          break;
        case 9:
          // (, line 292
          // <-, line 292
          slice_from("\u03B2\u03C5\u03B6\u03B1\u03BD\u03C4");
          break;
        case 10:
          // (, line 293
          // <-, line 293
          slice_from("\u03B8\u03B5\u03B1\u03C4\u03C1");
          break;
      }
    }
    return true;
  }

  private boolean r_steps7() {
    // (, line 299
    // [, line 300
    ket = cursor;
    // substring, line 300
    if (find_among_b(a_20) == 0) {
      return false;
    }
    // ], line 300
    bra = cursor;
    // (, line 301
    // delete, line 302
    slice_del();
    // unset test1, line 303
    B_test1 = false;
    // [, line 304
    ket = cursor;
    // ], line 304
    bra = cursor;
    // substring, line 304
    if (find_among_b(a_19) == 0) {
      return false;
    }
    // atlimit, line 304
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 306
    // <-, line 306
    slice_from("\u03B1\u03C1\u03B1\u03BA");
    return true;
  }

  private boolean r_steps8() {
    // (, line 312
    // [, line 313
    ket = cursor;
    // substring, line 313
    if (find_among_b(a_23) == 0) {
      return false;
    }
    // ], line 313
    bra = cursor;
    // (, line 314
    // delete, line 315
    slice_del();
    // unset test1, line 316
    B_test1 = false;
    // or, line 323
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 317
        // [, line 317
        ket = cursor;
        // ], line 317
        bra = cursor;
        // substring, line 317
        if (find_among_b(a_21) == 0) {
          break lab1;
        }
        // atlimit, line 317
        if (cursor > limit_backward) {
          break lab1;
        }
        // (, line 322
        // <-, line 322
        slice_from("\u03B1\u03BA");
        break lab0;
      }
      cursor = limit - v_1;
      lab2: {
        // (, line 324
        // [, line 324
        ket = cursor;
        // ], line 324
        bra = cursor;
        // substring, line 324
        if (find_among_b(a_22) == 0) {
          break lab2;
        }
        // atlimit, line 324
        if (cursor > limit_backward) {
          break lab2;
        }
        // (, line 327
        // <-, line 327
        slice_from("\u03B9\u03C4\u03C3");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 329
      // [, line 329
      ket = cursor;
      // ], line 329
      bra = cursor;
      // literal, line 329
      if (!(eq_s_b("\u03BA\u03BF\u03C1"))) {
        return false;
      }
      // <-, line 329
      slice_from("\u03B9\u03C4\u03C3");
    }
    return true;
  }

  private boolean r_steps9() {
    // (, line 334
    // [, line 335
    ket = cursor;
    // substring, line 335
    if (find_among_b(a_26) == 0) {
      return false;
    }
    // ], line 335
    bra = cursor;
    // (, line 336
    // delete, line 337
    slice_del();
    // unset test1, line 338
    B_test1 = false;
    // or, line 341
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 339
        // [, line 339
        ket = cursor;
        // ], line 339
        bra = cursor;
        // substring, line 339
        if (find_among_b(a_24) == 0) {
          break lab1;
        }
        // atlimit, line 339
        if (cursor > limit_backward) {
          break lab1;
        }
        // (, line 340
        // <-, line 340
        slice_from("\u03B9\u03B4");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 342
      // [, line 342
      ket = cursor;
      // ], line 342
      bra = cursor;
      // substring, line 342
      if (find_among_b(a_25) == 0) {
        return false;
      }
      // (, line 343
      // <-, line 343
      slice_from("\u03B9\u03B4");
    }
    return true;
  }

  private boolean r_steps10() {
    // (, line 349
    // [, line 350
    ket = cursor;
    // substring, line 350
    if (find_among_b(a_28) == 0) {
      return false;
    }
    // ], line 350
    bra = cursor;
    // (, line 351
    // delete, line 352
    slice_del();
    // unset test1, line 353
    B_test1 = false;
    // [, line 354
    ket = cursor;
    // ], line 354
    bra = cursor;
    // substring, line 354
    if (find_among_b(a_27) == 0) {
      return false;
    }
    // atlimit, line 354
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 356
    // <-, line 356
    slice_from("\u03B9\u03C3\u03BA");
    return true;
  }

  private boolean r_step2a() {
    // (, line 362
    // [, line 363
    ket = cursor;
    // substring, line 363
    if (find_among_b(a_29) == 0) {
      return false;
    }
    // ], line 363
    bra = cursor;
    // (, line 364
    // delete, line 364
    slice_del();
    // not, line 366
    {
      int v_1 = limit - cursor;
      lab0: {
        // (, line 366
        // [, line 366
        ket = cursor;
        // substring, line 366
        if (find_among_b(a_30) == 0) {
          break lab0;
        }
        // ], line 366
        bra = cursor;
        return false;
      }
      cursor = limit - v_1;
    }
    // <+, line 369
    {
      int c = cursor;
      insert(cursor, cursor, "\u03B1\u03B4");
      cursor = c;
    }
    return true;
  }

  private boolean r_step2b() {
    // (, line 372
    // [, line 373
    ket = cursor;
    // substring, line 373
    if (find_among_b(a_31) == 0) {
      return false;
    }
    // ], line 373
    bra = cursor;
    // (, line 374
    // delete, line 374
    slice_del();
    // [, line 376
    ket = cursor;
    // ], line 376
    bra = cursor;
    // substring, line 376
    if (find_among_b(a_32) == 0) {
      return false;
    }
    // (, line 377
    // <-, line 377
    slice_from("\u03B5\u03B4");
    return true;
  }

  private boolean r_step2c() {
    // (, line 381
    // [, line 382
    ket = cursor;
    // substring, line 382
    if (find_among_b(a_33) == 0) {
      return false;
    }
    // ], line 382
    bra = cursor;
    // (, line 383
    // delete, line 383
    slice_del();
    // [, line 385
    ket = cursor;
    // ], line 385
    bra = cursor;
    // substring, line 385
    if (find_among_b(a_34) == 0) {
      return false;
    }
    // (, line 387
    // <-, line 387
    slice_from("\u03BF\u03C5\u03B4");
    return true;
  }

  private boolean r_step2d() {
    // (, line 391
    // [, line 392
    ket = cursor;
    // substring, line 392
    if (find_among_b(a_35) == 0) {
      return false;
    }
    // ], line 392
    bra = cursor;
    // (, line 393
    // delete, line 393
    slice_del();
    // unset test1, line 393
    B_test1 = false;
    // [, line 395
    ket = cursor;
    // ], line 395
    bra = cursor;
    // substring, line 395
    if (find_among_b(a_36) == 0) {
      return false;
    }
    // atlimit, line 395
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 396
    // <-, line 396
    slice_from("\u03B5");
    return true;
  }

  private boolean r_step3() {
    // (, line 400
    // [, line 401
    ket = cursor;
    // substring, line 401
    if (find_among_b(a_37) == 0) {
      return false;
    }
    // ], line 401
    bra = cursor;
    // (, line 402
    // delete, line 402
    slice_del();
    // unset test1, line 402
    B_test1 = false;
    // (, line 404
    // [, line 404
    ket = cursor;
    // ], line 404
    bra = cursor;
    if (!(in_grouping_b(g_v, 945, 969))) {
      return false;
    }
    // <-, line 404
    slice_from("\u03B9");
    return true;
  }

  private boolean r_step4() {
    // (, line 407
    // [, line 408
    ket = cursor;
    // substring, line 408
    if (find_among_b(a_38) == 0) {
      return false;
    }
    // ], line 408
    bra = cursor;
    // (, line 409
    // delete, line 409
    slice_del();
    // unset test1, line 409
    B_test1 = false;
    // or, line 411
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 411
        // [, line 411
        ket = cursor;
        // ], line 411
        bra = cursor;
        if (!(in_grouping_b(g_v, 945, 969))) {
          break lab1;
        }
        // <-, line 411
        slice_from("\u03B9\u03BA");
        break lab0;
      }
      cursor = limit - v_1;
      // [, line 412
      ket = cursor;
    }
    // ], line 412
    bra = cursor;
    // substring, line 412
    if (find_among_b(a_39) == 0) {
      return false;
    }
    // atlimit, line 412
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 417
    // <-, line 417
    slice_from("\u03B9\u03BA");
    return true;
  }

  private boolean r_step5a() {
    // (, line 421
    // do, line 422
    int v_1 = limit - cursor;
    lab0: {
      // (, line 422
      // literal, line 422
      if (!(eq_s_b("\u03B1\u03B3\u03B1\u03BC\u03B5"))) {
        break lab0;
      }
      // atlimit, line 422
      if (cursor > limit_backward) {
        break lab0;
      }
      // <-, line 422
      slice_from("\u03B1\u03B3\u03B1\u03BC");
    }
    cursor = limit - v_1;
    // do, line 423
    int v_2 = limit - cursor;
    lab1: {
      // (, line 423
      // [, line 424
      ket = cursor;
      // substring, line 424
      if (find_among_b(a_40) == 0) {
        break lab1;
      }
      // ], line 424
      bra = cursor;
      // (, line 425
      // delete, line 425
      slice_del();
      // unset test1, line 425
      B_test1 = false;
    }
    cursor = limit - v_2;
    // [, line 428
    ket = cursor;
    // literal, line 428
    if (!(eq_s_b("\u03B1\u03BC\u03B5"))) {
      return false;
    }
    // ], line 428
    bra = cursor;
    // delete, line 429
    slice_del();
    // unset test1, line 430
    B_test1 = false;
    // [, line 431
    ket = cursor;
    // ], line 431
    bra = cursor;
    // substring, line 431
    if (find_among_b(a_41) == 0) {
      return false;
    }
    // atlimit, line 431
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 433
    // <-, line 433
    slice_from("\u03B1\u03BC");
    return true;
  }

  private boolean r_step5b() {
    // (, line 437
    // do, line 438
    int v_1 = limit - cursor;
    lab0: {
      // (, line 438
      // [, line 439
      ket = cursor;
      // substring, line 439
      if (find_among_b(a_43) == 0) {
        break lab0;
      }
      // ], line 439
      bra = cursor;
      // (, line 441
      // delete, line 442
      slice_del();
      // unset test1, line 443
      B_test1 = false;
      // [, line 444
      ket = cursor;
      // ], line 444
      bra = cursor;
      // substring, line 444
      if (find_among_b(a_42) == 0) {
        break lab0;
      }
      // atlimit, line 444
      if (cursor > limit_backward) {
        break lab0;
      }
      // (, line 445
      // <-, line 445
      slice_from("\u03B1\u03B3\u03B1\u03BD");
    }
    cursor = limit - v_1;
    // [, line 450
    ket = cursor;
    // literal, line 450
    if (!(eq_s_b("\u03B1\u03BD\u03B5"))) {
      return false;
    }
    // ], line 450
    bra = cursor;
    // delete, line 451
    slice_del();
    // unset test1, line 452
    B_test1 = false;
    // or, line 453
    lab1: {
      int v_2 = limit - cursor;
      lab2: {
        // (, line 453
        // [, line 453
        ket = cursor;
        // ], line 453
        bra = cursor;
        if (!(in_grouping_b(g_v2, 945, 969))) {
          break lab2;
        }
        // <-, line 453
        slice_from("\u03B1\u03BD");
        break lab1;
      }
      cursor = limit - v_2;
      // [, line 454
      ket = cursor;
    }
    // ], line 454
    bra = cursor;
    // substring, line 454
    if (find_among_b(a_44) == 0) {
      return false;
    }
    // atlimit, line 454
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 471
    // <-, line 471
    slice_from("\u03B1\u03BD");
    return true;
  }

  private boolean r_step5c() {
    // (, line 475
    // do, line 476
    int v_1 = limit - cursor;
    lab0: {
      // (, line 476
      // [, line 477
      ket = cursor;
      // substring, line 477
      if (find_among_b(a_45) == 0) {
        break lab0;
      }
      // ], line 477
      bra = cursor;
      // (, line 478
      // delete, line 478
      slice_del();
      // unset test1, line 478
      B_test1 = false;
    }
    cursor = limit - v_1;
    // [, line 481
    ket = cursor;
    // literal, line 481
    if (!(eq_s_b("\u03B5\u03C4\u03B5"))) {
      return false;
    }
    // ], line 481
    bra = cursor;
    // delete, line 482
    slice_del();
    // unset test1, line 483
    B_test1 = false;
    // or, line 484
    lab1: {
      int v_2 = limit - cursor;
      lab2: {
        // (, line 484
        // [, line 484
        ket = cursor;
        // ], line 484
        bra = cursor;
        if (!(in_grouping_b(g_v2, 945, 969))) {
          break lab2;
        }
        // <-, line 484
        slice_from("\u03B5\u03C4");
        break lab1;
      }
      cursor = limit - v_2;
      lab3: {
        // (, line 485
        // [, line 485
        ket = cursor;
        // ], line 485
        bra = cursor;
        // substring, line 485
        if (find_among_b(a_46) == 0) {
          break lab3;
        }
        // (, line 489
        // <-, line 489
        slice_from("\u03B5\u03C4");
        break lab1;
      }
      cursor = limit - v_2;
      // [, line 491
      ket = cursor;
    }
    // ], line 491
    bra = cursor;
    // substring, line 491
    if (find_among_b(a_47) == 0) {
      return false;
    }
    // atlimit, line 491
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 495
    // <-, line 495
    slice_from("\u03B5\u03C4");
    return true;
  }

  private boolean r_step5d() {
    // (, line 499
    // [, line 500
    ket = cursor;
    // substring, line 500
    if (find_among_b(a_48) == 0) {
      return false;
    }
    // ], line 500
    bra = cursor;
    // (, line 501
    // delete, line 502
    slice_del();
    // unset test1, line 503
    B_test1 = false;
    // or, line 504
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 504
        // [, line 504
        ket = cursor;
        // ], line 504
        bra = cursor;
        // literal, line 504
        if (!(eq_s_b("\u03B1\u03C1\u03C7"))) {
          break lab1;
        }
        // atlimit, line 504
        if (cursor > limit_backward) {
          break lab1;
        }
        // <-, line 504
        slice_from("\u03BF\u03BD\u03C4");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 505
      // [, line 505
      ket = cursor;
      // ], line 505
      bra = cursor;
      // literal, line 505
      if (!(eq_s_b("\u03BA\u03C1\u03B5"))) {
        return false;
      }
      // <-, line 505
      slice_from("\u03C9\u03BD\u03C4");
    }
    return true;
  }

  private boolean r_step5e() {
    // (, line 510
    // [, line 511
    ket = cursor;
    // substring, line 511
    if (find_among_b(a_49) == 0) {
      return false;
    }
    // ], line 511
    bra = cursor;
    // (, line 512
    // delete, line 513
    slice_del();
    // unset test1, line 514
    B_test1 = false;
    // (, line 515
    // [, line 515
    ket = cursor;
    // ], line 515
    bra = cursor;
    // literal, line 515
    if (!(eq_s_b("\u03BF\u03BD"))) {
      return false;
    }
    // atlimit, line 515
    if (cursor > limit_backward) {
      return false;
    }
    // <-, line 515
    slice_from("\u03BF\u03BC\u03B1\u03C3\u03C4");
    return true;
  }

  private boolean r_step5f() {
    // (, line 520
    // do, line 521
    int v_1 = limit - cursor;
    lab0: {
      // (, line 521
      // [, line 522
      ket = cursor;
      // literal, line 522
      if (!(eq_s_b("\u03B9\u03B5\u03C3\u03C4\u03B5"))) {
        break lab0;
      }
      // ], line 522
      bra = cursor;
      // delete, line 523
      slice_del();
      // unset test1, line 524
      B_test1 = false;
      // [, line 525
      ket = cursor;
      // ], line 525
      bra = cursor;
      // substring, line 525
      if (find_among_b(a_50) == 0) {
        break lab0;
      }
      // atlimit, line 525
      if (cursor > limit_backward) {
        break lab0;
      }
      // (, line 526
      // <-, line 526
      slice_from("\u03B9\u03B5\u03C3\u03C4");
    }
    cursor = limit - v_1;
    // [, line 529
    ket = cursor;
    // literal, line 529
    if (!(eq_s_b("\u03B5\u03C3\u03C4\u03B5"))) {
      return false;
    }
    // ], line 529
    bra = cursor;
    // delete, line 530
    slice_del();
    // unset test1, line 531
    B_test1 = false;
    // [, line 532
    ket = cursor;
    // ], line 532
    bra = cursor;
    // substring, line 532
    if (find_among_b(a_51) == 0) {
      return false;
    }
    // atlimit, line 532
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 534
    // <-, line 534
    slice_from("\u03B9\u03B5\u03C3\u03C4");
    return true;
  }

  private boolean r_step5g() {
    // (, line 538
    // do, line 539
    int v_1 = limit - cursor;
    lab0: {
      // (, line 539
      // [, line 540
      ket = cursor;
      // substring, line 540
      if (find_among_b(a_52) == 0) {
        break lab0;
      }
      // ], line 540
      bra = cursor;
      // (, line 541
      // delete, line 541
      slice_del();
      // unset test1, line 541
      B_test1 = false;
    }
    cursor = limit - v_1;
    // [, line 544
    ket = cursor;
    // substring, line 544
    if (find_among_b(a_55) == 0) {
      return false;
    }
    // ], line 544
    bra = cursor;
    // (, line 545
    // delete, line 546
    slice_del();
    // unset test1, line 547
    B_test1 = false;
    // or, line 550
    lab1: {
      int v_2 = limit - cursor;
      lab2: {
        // (, line 548
        // [, line 548
        ket = cursor;
        // ], line 548
        bra = cursor;
        // substring, line 548
        if (find_among_b(a_53) == 0) {
          break lab2;
        }
        // (, line 549
        // <-, line 549
        slice_from("\u03B7\u03BA");
        break lab1;
      }
      cursor = limit - v_2;
      // (, line 551
      // [, line 551
      ket = cursor;
      // ], line 551
      bra = cursor;
      // substring, line 551
      if (find_among_b(a_54) == 0) {
        return false;
      }
      // atlimit, line 551
      if (cursor > limit_backward) {
        return false;
      }
      // (, line 552
      // <-, line 552
      slice_from("\u03B7\u03BA");
    }
    return true;
  }

  private boolean r_step5h() {
    // (, line 558
    // [, line 559
    ket = cursor;
    // substring, line 559
    if (find_among_b(a_58) == 0) {
      return false;
    }
    // ], line 559
    bra = cursor;
    // (, line 560
    // delete, line 561
    slice_del();
    // unset test1, line 562
    B_test1 = false;
    // or, line 567
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 563
        // [, line 563
        ket = cursor;
        // ], line 563
        bra = cursor;
        // substring, line 563
        if (find_among_b(a_56) == 0) {
          break lab1;
        }
        // (, line 565
        // <-, line 565
        slice_from("\u03BF\u03C5\u03C3");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 568
      // [, line 568
      ket = cursor;
      // ], line 568
      bra = cursor;
      // substring, line 568
      if (find_among_b(a_57) == 0) {
        return false;
      }
      // atlimit, line 568
      if (cursor > limit_backward) {
        return false;
      }
      // (, line 572
      // <-, line 572
      slice_from("\u03BF\u03C5\u03C3");
    }
    return true;
  }

  private boolean r_step5i() {
    // (, line 578
    // [, line 579
    ket = cursor;
    // substring, line 579
    if (find_among_b(a_62) == 0) {
      return false;
    }
    // ], line 579
    bra = cursor;
    // (, line 580
    // delete, line 581
    slice_del();
    // unset test1, line 582
    B_test1 = false;
    // or, line 583
    lab0: {
      int v_1 = limit - cursor;
      lab1: {
        // (, line 583
        // [, line 583
        ket = cursor;
        // ], line 583
        bra = cursor;
        // literal, line 583
        if (!(eq_s_b("\u03BA\u03BF\u03BB\u03BB"))) {
          break lab1;
        }
        // <-, line 583
        slice_from("\u03B1\u03B3");
        break lab0;
      }
      cursor = limit - v_1;
      // (, line 583
      // not, line 584
      {
        int v_2 = limit - cursor;
        lab2: {
          // (, line 584
          // [, line 584
          ket = cursor;
          // substring, line 584
          if (find_among_b(a_59) == 0) {
            break lab2;
          }
          // ], line 584
          bra = cursor;
          return false;
        }
        cursor = limit - v_2;
      }
      // or, line 588
      lab3: {
        int v_3 = limit - cursor;
        lab4: {
          // (, line 585
          // [, line 585
          ket = cursor;
          // ], line 585
          bra = cursor;
          // substring, line 585
          if (find_among_b(a_60) == 0) {
            break lab4;
          }
          // (, line 587
          // <-, line 587
          slice_from("\u03B1\u03B3");
          break lab3;
        }
        cursor = limit - v_3;
        // (, line 589
        // [, line 589
        ket = cursor;
        // ], line 589
        bra = cursor;
        // substring, line 589
        if (find_among_b(a_61) == 0) {
          return false;
        }
        // atlimit, line 589
        if (cursor > limit_backward) {
          return false;
        }
        // (, line 595
        // <-, line 595
        slice_from("\u03B1\u03B3");
      }
    }
    return true;
  }

  private boolean r_step5j() {
    // (, line 602
    // [, line 603
    ket = cursor;
    // substring, line 603
    if (find_among_b(a_63) == 0) {
      return false;
    }
    // ], line 603
    bra = cursor;
    // (, line 604
    // delete, line 604
    slice_del();
    // unset test1, line 604
    B_test1 = false;
    // [, line 606
    ket = cursor;
    // ], line 606
    bra = cursor;
    // substring, line 606
    if (find_among_b(a_64) == 0) {
      return false;
    }
    // atlimit, line 606
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 607
    // <-, line 607
    slice_from("\u03B7\u03C3");
    return true;
  }

  private boolean r_step5k() {
    // (, line 611
    // [, line 612
    ket = cursor;
    // substring, line 612
    if (find_among_b(a_65) == 0) {
      return false;
    }
    // ], line 612
    bra = cursor;
    // (, line 613
    // delete, line 613
    slice_del();
    // unset test1, line 613
    B_test1 = false;
    // [, line 615
    ket = cursor;
    // ], line 615
    bra = cursor;
    // substring, line 615
    if (find_among_b(a_66) == 0) {
      return false;
    }
    // atlimit, line 615
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 617
    // <-, line 617
    slice_from("\u03B7\u03C3\u03C4");
    return true;
  }

  private boolean r_step5l() {
    // (, line 621
    // [, line 622
    ket = cursor;
    // substring, line 622
    if (find_among_b(a_67) == 0) {
      return false;
    }
    // ], line 622
    bra = cursor;
    // (, line 623
    // delete, line 623
    slice_del();
    // unset test1, line 623
    B_test1 = false;
    // [, line 625
    ket = cursor;
    // ], line 625
    bra = cursor;
    // substring, line 625
    if (find_among_b(a_68) == 0) {
      return false;
    }
    // atlimit, line 625
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 626
    // <-, line 626
    slice_from("\u03BF\u03C5\u03BD");
    return true;
  }

  private boolean r_step5m() {
    // (, line 630
    // [, line 631
    ket = cursor;
    // substring, line 631
    if (find_among_b(a_69) == 0) {
      return false;
    }
    // ], line 631
    bra = cursor;
    // (, line 632
    // delete, line 632
    slice_del();
    // unset test1, line 632
    B_test1 = false;
    // [, line 634
    ket = cursor;
    // ], line 634
    bra = cursor;
    // substring, line 634
    if (find_among_b(a_70) == 0) {
      return false;
    }
    // atlimit, line 634
    if (cursor > limit_backward) {
      return false;
    }
    // (, line 636
    // <-, line 636
    slice_from("\u03BF\u03C5\u03BC");
    return true;
  }

  private boolean r_step6() {
    // (, line 640
    // do, line 641
    int v_1 = limit - cursor;
    lab0: {
      // (, line 641
      // [, line 642
      ket = cursor;
      // substring, line 642
      if (find_among_b(a_71) == 0) {
        break lab0;
      }
      // ], line 642
      bra = cursor;
      // (, line 643
      // <-, line 643
      slice_from("\u03BC\u03B1");
    }
    cursor = limit - v_1;
    // Boolean test test1, line 646
    if (!(B_test1)) {
      return false;
    }
    // [, line 647
    ket = cursor;
    // substring, line 647
    if (find_among_b(a_72) == 0) {
      return false;
    }
    // ], line 647
    bra = cursor;
    // (, line 657
    // delete, line 657
    slice_del();
    return true;
  }

  private boolean r_step7() {
    // (, line 661
    // [, line 662
    ket = cursor;
    // substring, line 662
    if (find_among_b(a_73) == 0) {
      return false;
    }
    // ], line 662
    bra = cursor;
    // (, line 663
    // delete, line 663
    slice_del();
    return true;
  }

  public boolean stem() {
    // (, line 668
    // backwards, line 669
    limit_backward = cursor;
    cursor = limit;
    // (, line 669
    // do, line 670
    int v_1 = limit - cursor;
    // call tolower, line 670
    r_tolower();
    cursor = limit - v_1;
    // call has_min_length, line 671
    if (!r_has_min_length()) {
      return false;
    }
    // set test1, line 672
    B_test1 = true;
    // do, line 673
    int v_2 = limit - cursor;
    // call step1, line 673
    r_step1();
    cursor = limit - v_2;
    // do, line 674
    int v_3 = limit - cursor;
    // call steps1, line 674
    r_steps1();
    cursor = limit - v_3;
    // do, line 675
    int v_4 = limit - cursor;
    // call steps2, line 675
    r_steps2();
    cursor = limit - v_4;
    // do, line 676
    int v_5 = limit - cursor;
    // call steps3, line 676
    r_steps3();
    cursor = limit - v_5;
    // do, line 677
    int v_6 = limit - cursor;
    // call steps4, line 677
    r_steps4();
    cursor = limit - v_6;
    // do, line 678
    int v_7 = limit - cursor;
    // call steps5, line 678
    r_steps5();
    cursor = limit - v_7;
    // do, line 679
    int v_8 = limit - cursor;
    // call steps6, line 679
    r_steps6();
    cursor = limit - v_8;
    // do, line 680
    int v_9 = limit - cursor;
    // call steps7, line 680
    r_steps7();
    cursor = limit - v_9;
    // do, line 681
    int v_10 = limit - cursor;
    // call steps8, line 681
    r_steps8();
    cursor = limit - v_10;
    // do, line 682
    int v_11 = limit - cursor;
    // call steps9, line 682
    r_steps9();
    cursor = limit - v_11;
    // do, line 683
    int v_12 = limit - cursor;
    // call steps10, line 683
    r_steps10();
    cursor = limit - v_12;
    // do, line 684
    int v_13 = limit - cursor;
    // call step2a, line 684
    r_step2a();
    cursor = limit - v_13;
    // do, line 685
    int v_14 = limit - cursor;
    // call step2b, line 685
    r_step2b();
    cursor = limit - v_14;
    // do, line 686
    int v_15 = limit - cursor;
    // call step2c, line 686
    r_step2c();
    cursor = limit - v_15;
    // do, line 687
    int v_16 = limit - cursor;
    // call step2d, line 687
    r_step2d();
    cursor = limit - v_16;
    // do, line 688
    int v_17 = limit - cursor;
    // call step3, line 688
    r_step3();
    cursor = limit - v_17;
    // do, line 689
    int v_18 = limit - cursor;
    // call step4, line 689
    r_step4();
    cursor = limit - v_18;
    // do, line 690
    int v_19 = limit - cursor;
    // call step5a, line 690
    r_step5a();
    cursor = limit - v_19;
    // do, line 691
    int v_20 = limit - cursor;
    // call step5b, line 691
    r_step5b();
    cursor = limit - v_20;
    // do, line 692
    int v_21 = limit - cursor;
    // call step5c, line 692
    r_step5c();
    cursor = limit - v_21;
    // do, line 693
    int v_22 = limit - cursor;
    // call step5d, line 693
    r_step5d();
    cursor = limit - v_22;
    // do, line 694
    int v_23 = limit - cursor;
    // call step5e, line 694
    r_step5e();
    cursor = limit - v_23;
    // do, line 695
    int v_24 = limit - cursor;
    // call step5f, line 695
    r_step5f();
    cursor = limit - v_24;
    // do, line 696
    int v_25 = limit - cursor;
    // call step5g, line 696
    r_step5g();
    cursor = limit - v_25;
    // do, line 697
    int v_26 = limit - cursor;
    // call step5h, line 697
    r_step5h();
    cursor = limit - v_26;
    // do, line 698
    int v_27 = limit - cursor;
    // call step5j, line 698
    r_step5j();
    cursor = limit - v_27;
    // do, line 699
    int v_28 = limit - cursor;
    // call step5i, line 699
    r_step5i();
    cursor = limit - v_28;
    // do, line 700
    int v_29 = limit - cursor;
    // call step5k, line 700
    r_step5k();
    cursor = limit - v_29;
    // do, line 701
    int v_30 = limit - cursor;
    // call step5l, line 701
    r_step5l();
    cursor = limit - v_30;
    // do, line 702
    int v_31 = limit - cursor;
    // call step5m, line 702
    r_step5m();
    cursor = limit - v_31;
    // do, line 703
    int v_32 = limit - cursor;
    // call step6, line 703
    r_step6();
    cursor = limit - v_32;
    // do, line 704
    int v_33 = limit - cursor;
    // call step7, line 704
    r_step7();
    cursor = limit - v_33;
    cursor = limit_backward;
    return true;
  }

  @Override
  public boolean equals(Object o) {
    return o instanceof greekStemmer;
  }

  @Override
  public int hashCode() {
    return greekStemmer.class.getName().hashCode();
  }



}

