package com.computablefacts.nona;

public enum eCategory {
  UNKNOWN, ADDITIVE_OPERATORS, ASSIGNMENT_OPERATORS, BOOLEAN_LOGIC_OPERATORS, COMPARISON_OPERATORS, CONTROL_FLOW_OPERATORS, CSV_OPERATORS, DATE_OPERATORS, JSON_OPERATORS, LIST_OPERATORS, MACHINE_LEARNING_OPERATORS, MATHEMATICAL_OPERATORS, MULTIPLICATIVE_OPERATORS, PATTERN_OPERATORS, PROBLOG_OPERATORS, STRING_OPERATORS
}
